ICMSLST-1977 Emails for firearms and section 5 authorities
uktrade/icms pull request #1075
Opened 2023-05-16 16:38 UTC by mikeylockwood

2023-05-18 09:11 UTC, MattHolmes123 requested changes

2023-05-18 09:11 UTC, MattHolmes123 commented on web/tests/notify/test_notify.py
> +        notify.send_firearms_authority_expiry_notification()
Checked with Michael and this isn't needed

2023-05-18 09:15 UTC, mikeylockwood commented on config/celery.py
> +}
I think it's fine to have it run in all environments as it will just send a notification to the console in non prod environments

2023-05-18 09:21 UTC, mikeylockwood commented on web/notify/notify.py
> +    ).distinct()
V1 only sends the notification at the 30 day point

2023-05-18 09:22 UTC, mikeylockwood commented on web/notify/notify.py
> +    )
Oh I thought it also impacted filtering across those fields but I guess I'm wrong

2023-05-19 07:45 UTC, MattHolmes123 requested changes

2023-05-19 07:45 UTC, MattHolmes123 commented on web/domains/firearms/forms.py
> +        self.fields["other_archive_reason"].label = "Other"
set the `verbose_name` on the `other_archive_reason` model field to "Other"?
Same comment applies to `ArchiveSection5AuthorityForm`

2023-05-19 07:45 UTC, MattHolmes123 commented on web/domains/firearms/forms.py
> +        widgets = {"archive_reason": CheckboxSelectMultiple(choices=ArchiveReasonChoices.choices)}
`other_archive_reason` is mandatory when `archive_reason` is set to Other.
![image](https://github.com/uktrade/icms/assets/8921101/08d27e6e-8cb0-4af6-9cb1-41bcc83189e5)
Same comment applies to ArchiveSection5AuthorityForm

2023-05-19 07:45 UTC, MattHolmes123 commented on web/domains/firearms/views.py
It's a ModelForm now so shouldn't this be this to save the new fields:
```python
if form.is_valid():
    firearms = form.save(commit=False)
    firearms.is_active = False
    firearms.save()
```

Same comment applies to ArchiveSection5AuthorityForm as you've done it slightly different there.
(Double save as you didn't use commit=False)

2023-05-19 07:45 UTC, MattHolmes123 commented on web/domains/importer/views.py
> +            form.save()
use commit=False

2023-05-19 07:45 UTC, MattHolmes123 commented on web/templates/web/domains/importer/detail-firearms-authority.html
> +    {{ application_field(firearms_authority.further_details|nl2br or "N/A", "End Date") }}
Two fields with the same name?

2023-05-19 07:45 UTC, MattHolmes123 commented on web/templates/web/domains/importer/detail-firearms-authority.html
> +        <table class="setout`List">
You have a backtick in the table class.

2023-05-19 07:45 UTC, MattHolmes123 commented on web/templates/web/domains/importer/detail-section5-authority.html
> +    {{ application_field(section5.further_details|nl2br or "N/A", "End Date") }}
Same mistake here.

2023-05-19 09:50 UTC, merged