ICMSLST-1961 Reopen case email
uktrade/icms pull request #1077
Opened 2023-05-17 15:26 UTC by marcuspp

2023-05-18 06:52 UTC, MattHolmes123 commented on web/domains/case/views/views_search.py
> +        with transaction.atomic():
The post method is already atomic:
`@method_decorator(transaction.atomic, name="post")`

2023-05-18 06:53 UTC, MattHolmes123 commented on web/domains/case/views/views_search.py
> +        with transaction.atomic():
I don't really mind which we use but not both.

2023-05-18 07:02 UTC, MattHolmes123 commented on web/notify/constants.py
> +class DatabaseEmailTemplate(enum.Enum):
We are running ICMS using pythin 3.11.
Let's use StrEnum

```
>>> from enum import Enum, StrEnum
>>> class Foo(Enum):
...     VAL = "ASDF"
... 
>>> class Bar(StrEnum):
...     VAL = "ASDF"
... 
>>> print(Foo.VAL == "ASDF")
False
>>> print(Foo.VAL.value == "ASDF")
True
>>> print(Bar.VAL == "ASDF")
True
>>> print(Bar.VAL.value == "ASDF")
True
>>> 
```

2023-05-18 07:04 UTC, MattHolmes123 requested changes
added a few comments.

2023-05-19 08:12 UTC, marcuspp commented on web/domains/case/views/views_search.py
> +        with transaction.atomic():
👍 I didn't notice the decorator so I have just removed the with statement

2023-05-19 08:13 UTC, marcuspp commented on web/notify/constants.py
> +class DatabaseEmailTemplate(enum.Enum):
Updated! I need to the read the whats new in 3.11 :-)

2023-05-19 14:01 UTC, merged