ICMLST-1969 Variation Request emails
uktrade/icms pull request #1088
Opened 2023-05-30 14:21 UTC by marcuspp

2023-05-30 17:03 UTC, marcuspp commented on web/notify/email.py
> +
Not 100% sure if the recipients are correct.

2023-06-02 08:17 UTC, MattHolmes123 requested changes

2023-06-02 08:17 UTC, MattHolmes123 commented on web/domains/case/views/views_misc.py
> +                    send_variation_request_email(
This should probably be moved to the bottom of the function.
Maybe after `send_refused_email`.
I just think triggering tasks to execute after everything else has successfully completed is a good idea.

2023-06-02 08:17 UTC, MattHolmes123 commented on web/notify/email.py
> +        return f"Variation on application reference {application.reference} has been refused by ILB"
Not required but I think match statements get better the more if statements you have.
also raise a `ValueError` for unsupported description values

2023-06-02 13:09 UTC, marcuspp commented on web/notify/email.py
> +
Updated to case owner

2023-06-02 14:05 UTC, MattHolmes123 commented on web/notify/email.py
> +    if description in [VariationRequestDescription.CANCELLED]:
change to ==

2023-06-02 14:07 UTC, MattHolmes123 approved these changes
Added a minor comment.

2023-06-02 14:33 UTC, merged