ICMSLST-2166 - Access Request Approval Opened
uktrade/icms pull request #1163
Opened 2023-08-21 15:04 UTC by marcuspp

2023-08-21 15:50 UTC, mikeylockwood approved these changes

2023-08-22 07:36 UTC, MattHolmes123 requested changes

2023-08-22 07:36 UTC, MattHolmes123 commented on web/mail/emails.py
> +        email.send()
This is a general comment about all emails classes so far, is there a reason you don't just do this:
```python
ExporterAccessRequestApprovalOpened(
    approval_request=approval_request, to=recipients
).send()
```
The mail backend iterates over the recipients.
It also changes get_template_id & get_personalisation from O(n) to O(1)

2023-08-22 08:40 UTC, MattHolmes123 commented on web/mail/emails.py
> +        AccessRequestEmail(access_request=access_request, to=[recipient]).send()
Need to remove the for loops and replace `to=[recipient]` with `to=recipients`

2023-08-22 09:02 UTC, MattHolmes123 approved these changes

2023-08-22 11:49 UTC, merged