ICMSLST-1406 Generate CFS Schedule PDFs
uktrade/icms pull request #1176
Opened 2023-09-07 12:31 UTC by mikeylockwood

2023-09-08 15:10 UTC, marcuspp approved these changes

2023-09-11 15:58 UTC, MattHolmes123 requested changes

2023-09-11 15:58 UTC, MattHolmes123 commented on web/domains/case/views/views_misc.py
>          }
This needs reverting to use `certificate_links` and not hard code urls in the template.
Look at the import block, this is used for both the pre-sign and the final view (so the links change).
An exception is being thrown currenntly when viewing the "pre-sign" version of the screen as it's trying to fetch documents from S3 that dont exist yet.

2023-09-11 16:03 UTC, MattHolmes123 commented on web/domains/case/tasks.py
> +    with transaction.atomic():
Suppose you'd move your comment below in to the if block as well.
# TODO: Revisit when we can generate an export certificate:
# https://uktrade.atlassian.net/browse/ICMSLST-1407
# https://uktrade.atlassian.net/browse/ICMSLST-1408

2023-09-12 11:03 UTC, MattHolmes123 requested changes

2023-09-12 11:03 UTC, MattHolmes123 commented on web/static/web/css/pdfs/export-certificate-style.css
> +}
Missing newline at end of the file.

2023-09-12 13:15 UTC, MattHolmes123 approved these changes

2023-09-12 13:22 UTC, merged