ICMSLST-2412 ILB Admin Tool for managing signatures in documents
uktrade/icms pull request #1267
Opened 2023-12-19 13:44 UTC by mikeylockwood

2023-12-21 10:42 UTC, marcuspp commented on web/domains/signature/views.py
> +                request, f'Signature "{active_signature.name}" is alreay the active signature.'
typo `alreay`

2023-12-21 10:42 UTC, marcuspp commented on web/templates/web/domains/signature/list-view.html
> +    The active siganture will appear on all documents and there must always be one active signature.
Typo `siganture`

2023-12-21 10:42 UTC, marcuspp commented on web/tests/domains/case/_import/test_views.py
> +@pytest.fixture(autouse=True)
This block is repeated in 5 different files. Anyway this could be put in conftest instead?

2023-12-21 13:07 UTC, MattHolmes123 requested changes
Regarding this comment: 
Adds signature management to /signature for ilb_admin role

`ilb_admin` is a permssion not a role, therefore the "Sanctions Case Officer" group will also have access to all these views as it currently stands.

2023-12-21 14:14 UTC, MattHolmes123 commented on web/static/web/js/components/signature.js
> +$(document).ready(function () {
No jquery, we've done this in many places with vanilla JS:
```javascript
window.addEventListener('load', function (event) {
  foo();
});
```

2023-12-21 14:14 UTC, MattHolmes123 commented on web/static/web/js/components/signature.js
> +  signatoryInput.onchange = signatoryTextChange;
Allow multiple onchange events. 
```javascript
  signatoryInput.addEventListener("change", signatoryTextChange);
```

2023-12-21 14:14 UTC, MattHolmes123 commented on web/domains/signature/views.py
> +def set_active_signature(request: AuthenticatedHttpRequest, *, pk: int):
If you remember we settled on more specific url kwargs.
`tablename_pk` instead of `pk`

2023-12-21 14:17 UTC, mikeylockwood commented on web/domains/signature/models.py
> +    return dt.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
Only useful to make it easier to override it in the tests

2023-12-21 14:26 UTC, mikeylockwood commented on web/tests/domains/signature/test_views.py
> +    assert signature.history == f"2023-12-19 12:51:59 - Set active by {ilb_admin_user}."
That would explain why they are missing from the coverage report. I missed that

2023-12-21 15:03 UTC, MattHolmes123 commented on web/domains/signature/models.py
> +    return dt.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
Use `@freezegun.freeze_time("2020-01-01 12:00:00")` if you want an expected time value.

2023-12-22 11:20 UTC, MattHolmes123 approved these changes

2023-12-22 15:49 UTC, merged