ICMSLST-2422 - CSP headers
uktrade/icms pull request #1279
Opened 2024-01-10 20:21 UTC by chris-pettinga

Added CSP headers via django-csp-middleware

Added nonces to all script elements

Added tests

2024-01-11 14:24 UTC, mikeylockwood commented on web/templates/partial/js_constants.html
> +<script nonce="{{request.csp_nonce}}" type="application/javascript">
Personally prefer template variables to have a space between the brackets e.g. `{{ request.csp_nonce }}` but that's  being very petty. Fine also to leave it

2024-01-11 14:26 UTC, mikeylockwood approved these changes

2024-01-11 15:02 UTC, chris-pettinga commented on config/settings.py
> +CSP_REPORT_URI = env.csp_report_uri
They are picked up by the django-csp-middleware package which then uses them to craft the correct response header

2024-01-11 15:03 UTC, chris-pettinga commented on web/templates/partial/js_constants.html
> +<script nonce="{{request.csp_nonce}}" type="application/javascript">
Agreed, will change now

2024-01-12 09:28 UTC, MattHolmes123 requested changes

2024-01-12 09:28 UTC, MattHolmes123 commented on config/settings.py
> +CSP_REPORT_URI = env.csp_report_uri  # URL to send CSP violation reports to
Could you write the documentation without using inline comments please.

They are harder to read and are not consistent with the rest of the comments in the settings file

2024-01-12 09:28 UTC, MattHolmes123 commented on web/templates/base.html
> +    <iframe id="iframe-wrapper" src="about:blank" style="border: none; overflow: hidden; visibility: hidden; display: none;">&nbsp;</iframe>
I've just checked the src in V1 test and it looks like someone copied this over:
![image](https://github.com/uktrade/icms/assets/8921101/4f4fef4a-4201-4b6d-a4a9-e133971975e5)
Have a look in the v2 codebase but I think we can get rid of this

2024-01-12 09:28 UTC, MattHolmes123 commented on web/templates/web/domains/chief/_base.html
> +  <script nonce="{{ request.csp_nonce }}" type="text/javascript">
Nothing to do with this line but I've checked through the codebase and you've missed this inline script:
`web/templates/web/search-companies.html`
Probably because it doesn't specify the type:
`<script>`

2024-01-12 09:28 UTC, MattHolmes123 commented on config/env.py
> +    csp_report_uri: str = ""
How come we aren't adding an endpoint to report csp breaches to?
I added this view locally to test that it would send requests to an endpoint and it worked.
Not suggesting it's finished.

```
from web.utils.sentry import capture_message

@require_POST
@csrf_exempt
def csp_violation_report(request):
    if request.content_type == "application/csp-report":
        # TODO: Do something with the report
        ...
        capture_message("We've got a naughty script")
```

2024-01-12 09:28 UTC, MattHolmes123 commented on config/env.py
> +    csp_report_uri: str = ""
I can create a PR to your PR if you want to see what I did.

2024-01-12 10:47 UTC, chris-pettinga commented on config/env.py
> +    csp_report_uri: str = ""
Sentry provides a CSP reporting URI out-of-the-box which automatically deals with parsing the report. My concern was introducing noise from local environment CSP violations so I wanted to only include the REPORT_URI on deployed environments. What I'll do is hardcode the URI (as it's the same for all environments) and override it on local to be None, what do you think?

2024-01-12 11:04 UTC, MattHolmes123 commented on config/env.py
> +    csp_report_uri: str = ""
We shouldn't get any noise because isn't the goal to fix violations?
Thats cool about sentry for the deployed environments though.

2024-01-12 11:06 UTC, MattHolmes123 commented on config/env.py
> +    csp_report_uri: str = ""
Leave it as you have it now (as an environment variable)

2024-01-12 11:07 UTC, MattHolmes123 commented on config/env.py
> +    csp_report_uri: str = ""
Actually the type is wrong though.
CSP_REPORT_URI
    Set the report-uri directive. A tuple or list. Each URI can be a full or relative URI. None Note: This doesn’t use default-src as a fall-back.
    
    `csp_report_uri: list[str] = ""`

2024-01-12 11:08 UTC, chris-pettinga commented on web/templates/base.html
> +    <iframe id="iframe-wrapper" src="about:blank" style="border: none; overflow: hidden; visibility: hidden; display: none;">&nbsp;</iframe>
@MattHolmes123 - It's used in js.fox.core-footer.js:473. Seemingly as part of loading spinner functionality blocking double-clicks.

2024-01-12 11:12 UTC, MattHolmes123 commented on web/templates/base.html
> +    <iframe id="iframe-wrapper" src="about:blank" style="border: none; overflow: hidden; visibility: hidden; display: none;">&nbsp;</iframe>
core-footer.js is only 307 lines long?

2024-01-12 11:20 UTC, chris-pettinga commented on config/env.py
> +    csp_report_uri: str = ""
The goal is to get alerted of any violations via Sentry, and if someone is developing some JS quickly and locally, they may not bother with a nonce which will result in a (I think) noisy Sentry alert sent to all team members. I think it's cleaner to only bother with the alerts on deployed instances so we know that code is actually a bit more developed and perhaps ready to go into main

2024-01-12 11:20 UTC, chris-pettinga commented on config/env.py
> +    csp_report_uri: str = ""
Also just learnt that you can in fact include environment in the Sentry reporting URI, so we can perhaps solve this problem that way

2024-01-12 11:25 UTC, MattHolmes123 commented on config/env.py
> +    csp_report_uri: str = ""
I agree don't bother reporting to sentry locally, the example I added was from yesterday when I didn't even know sentry supported CSP.
The local endpoint would have just been used as a tool locally to tell the developer "hey you've added something invalid" so lets forget about it.

2024-01-12 17:02 UTC, MattHolmes123 commented on web/templates/web/search-companies.html
> +<script nonce="{{ request.csp_nonce }}">
Sorry there are actually several empty script tags like this:
`<script>`
Can you change them all to 
`<script nonce="{{ request.csp_nonce }}" type="text/javascript">`

2024-01-12 17:03 UTC, MattHolmes123 commented on web/templates/web/search-companies.html
> +<script nonce="{{ request.csp_nonce }}">
I find 5 on main:
![image](https://github.com/uktrade/icms/assets/8921101/6d7e9708-b24a-49d6-ba6a-cfc71793905a)

2024-01-12 18:53 UTC, chris-pettinga commented on web/templates/base.html
> +    <iframe id="iframe-wrapper" src="about:blank" style="border: none; overflow: hidden; visibility: hidden; display: none;">&nbsp;</iframe>
static/web/js/fox/core-footer.js? Maybe it was reduced when you removed old JS recently

2024-01-15 10:31 UTC, marcuspp approved these changes

2024-01-15 10:56 UTC, MattHolmes123 commented on web/templates/base.html
> +    <iframe id="iframe-wrapper" src="about:blank" style="border: none; overflow: hidden; visibility: hidden; display: none;">&nbsp;</iframe>
Yes @chris-pettinga it's one of the files I updated.

2024-01-15 12:29 UTC, MattHolmes123 approved these changes

2024-01-15 13:59 UTC, merged