ICMSLST-697 - Endesive digital signatures
uktrade/icms pull request #1296
Opened 2024-01-22 16:53 UTC by chris-pettinga

2024-01-22 17:11 UTC, MattHolmes123 commented on web/domains/signature/views.py
> +    permission_required = Perms.sys.ilb_admin
The `Perms.sys.manage_signatures` was used instead of `Perms.sys.ilb_admin` because these screens aren't used by Sanctions case officers.

2024-01-22 17:12 UTC, MattHolmes123 commented on web/domains/signature/views.py
> +    permission_required = Perms.sys.ilb_admin
Groups defined here:
`icms/web/management/commands/create_icms_groups.py`

2024-01-22 17:15 UTC, MattHolmes123 commented on web/utils/pdf/generator.py
> +from playwright.sync_api import sync_playwright
You haven't added playwright as a project dependency in requirements-base.txt

2024-01-22 17:28 UTC, MattHolmes123 commented on web/jinja2.py
> +        return css_file.read()
css_file_path is already a Path instance:
![image](https://github.com/uktrade/icms/assets/8921101/a484f275-38d5-4da7-8c2d-21b316e66c25)

2024-01-23 08:16 UTC, MattHolmes123 commented on web/domains/signature/views.py
> +    permission_required = Perms.sys.ilb_admin
Michael will have merged his PR and you won't have reset your local db.
This script does help when someone merges a PR that changes the db migrations:
icms/scripts/reset-local-docker-db

2024-01-23 08:20 UTC, MattHolmes123 commented on web/tests/utils/pdf/test_signer.py
> +import weasyprint
You've removed this as a dependency.
You you still need weasyprint for the tests or are you going to refactor these?

2024-01-23 09:11 UTC, mikeylockwood commented on web/templates/web/domains/signature/macros.html
> +            <img id="not_signed_image" src="data:jpg;base64,/9j/4AAQSkZJRgABAgEB1AHUAAD/2wDFAAwICA0IDREODhEXFRYVERQZGRkZFxoWFx4eHBogGx0dJx0bICInJycnJyIsLy8vLyw3Ozs7Nzs7Ozs7Ozs7OzsBDQsLDgsOEQ8PEhgRERE
Could the file be loaded as a base64 string rather than have all the characters in a macro? If this needs to be done in jinja could add a custom filter to do it

2024-01-23 09:13 UTC, mikeylockwood commented on web/tests/utils/pdf/test_signer.py
> +import weasyprint
These tests look like they were copied from the pyhanko pr, so will need to be refactored

2024-01-25 16:09 UTC, chris-pettinga commented on web/templates/web/domains/signature/macros.html
> +            <img id="not_signed_image" src="data:jpg;base64,/9j/4AAQSkZJRgABAgEB1AHUAAD/2wDFAAwICA0IDREODhEXFRYVERQZGRkZFxoWFx4eHBogGx0dJx0bICInJycnJyIsLy8vLyw3Ozs7Nzs7Ozs7Ozs7OzsBDQsLDgsOEQ8PEhgRERE
@mikeylockwood 
This whole bit of HTML has to be loaded raw into playwright for it to render a PDF, so unfortunately we can't use static file loading as playwright doesn't have access to the Django server.

Re. custom filter, not sure exactly what that would like, I'm cautious of adding a new filter which is only used once. Am I understanding correctly?

2024-01-25 16:52 UTC, mikeylockwood commented on web/templates/web/domains/signature/macros.html
> +            <img id="not_signed_image" src="data:jpg;base64,/9j/4AAQSkZJRgABAgEB1AHUAAD/2wDFAAwICA0IDREODhEXFRYVERQZGRkZFxoWFx4eHBogGx0dJx0bICInJycnJyIsLy8vLyw3Ozs7Nzs7Ozs7Ozs7OzsBDQsLDgsOEQ8PEhgRERE
I just think it would be annoying to change this image if the base64 string has to be saved in the macro / template. We define custom jinja functions and filters in `web/jinja2.py`. Filter was the wrong term, I meant global function.

I was thinking something like 
```
def img_to_base64(filepath):
    # returns file as base64 string
```

And then in the template
```
<img id="not_signed_image" src="data:jpg;base64,{{ img_to_base64('/path/to/file.png') }}" />
```

2024-01-25 18:30 UTC, chris-pettinga commented on web/templates/web/domains/signature/macros.html
> +            <img id="not_signed_image" src="data:jpg;base64,/9j/4AAQSkZJRgABAgEB1AHUAAD/2wDFAAwICA0IDREODhEXFRYVERQZGRkZFxoWFx4eHBogGx0dJx0bICInJycnJyIsLy8vLyw3Ozs7Nzs7Ozs7Ozs7OzsBDQsLDgsOEQ8PEhgRERE
Yes I see now, that's a good suggestion thanks.

2024-01-26 09:03 UTC, mikeylockwood commented on web/templates/pdf/export/cfs-certificate.html
> +	<p>
It looks like your ide is mixing tabs an spaces. Covert all tabs to spaces. Prefer 2 spaces in html files as there tends to be a lot of nested elements

2024-01-26 10:16 UTC, MattHolmes123 commented on Dockerfile
> +RUN apt-get update && apt-get install wget graphviz libgraphviz-dev gcc libpq-dev swig postgresql-client npm -y
Running `make setup` no longer works.
I assumed I just needed `swig` so did a `brew install swig`, is there anything else I need to install to get this branch working locally that you haven't documented?

2024-01-26 10:24 UTC, MattHolmes123 commented on web/templates/pdf/export/cfs-certificate.html
> +	<p>
I also prefer 2 spaces in html files and spaces everywhere.
Death to tabs :D

2024-01-26 10:26 UTC, MattHolmes123 commented on requirements-base.txt
> +pytest-playwright==0.4.2
I don't think this will work in CF / DBT Platform.
We should use the library instead of the pytest plugin:
https://playwright.dev/python/docs/library#pip
We also need to install playwright after we have the package: `playwright install`

2024-01-26 10:28 UTC, MattHolmes123 commented on Dockerfile
> +RUN apt-get update && apt-get install wget graphviz libgraphviz-dev gcc libpq-dev swig postgresql-client npm -y
Either way make setup should still work and have documentation for any extra packages needed to get this up and running.

2024-01-30 08:58 UTC, MattHolmes123 commented on Dockerfile
> +RUN apt-get update && apt-get install wget graphviz libgraphviz-dev gcc libpq-dev swig postgresql-client npm -y
Running make initial_setup still errors like before:

```
Building wheels for collected packages: pykcs11
  Building wheel for pykcs11 (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for pykcs11 (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [71 lines of output]
      running bdist_wheel
      running build
      running build_py
      running build_ext
      building 'PyKCS11._LowLevel' extension
      swigging src/pykcs11.i to src/pykcs11_wrap.cpp
      swig -python -c++ -o src/pykcs11_wrap.cpp src/pykcs11.i
      creating build
      creating build/temp.macosx-13.2-arm64-cpython-311
      creating build/temp.macosx-13.2-arm64-cpython-311/src
      clang -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/opt/homebrew/opt/openssl@3/include -Isrc -I/usr/local/include -I/Users/matthewholmes/work/icms/.venv/include -I/Users/matthewholmes/.pyenv/versions/3.11.2/include/python3.11 -c src/ck_attribute_smart.cpp -o build/temp.macosx-13.2-arm64-cpython-311/src/ck_attribute_smart.o
      clang -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/opt/homebrew/opt/openssl@3/include -Isrc -I/usr/local/include -I/Users/matthewholmes/work/icms/.venv/include -I/Users/matthewholmes/.pyenv/versions/3.11.2/include/python3.11 -c src/dyn_unix.c -o build/temp.macosx-13.2-arm64-cpython-311/src/dyn_unix.o
      clang -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/opt/homebrew/opt/openssl@3/include -Isrc -I/usr/local/include -I/Users/matthewholmes/work/icms/.venv/include -I/Users/matthewholmes/.pyenv/versions/3.11.2/include/python3.11 -c src/pkcs11lib.cpp -o build/temp.macosx-13.2-arm64-cpython-311/src/pkcs11lib.o
      clang -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/opt/homebrew/opt/openssl@3/include -Isrc -I/usr/local/include -I/Users/matthewholmes/work/icms/.venv/include -I/Users/matthewholmes/.pyenv/versions/3.11.2/include/python3.11 -c src/pykcs11.cpp -o build/temp.macosx-13.2-arm64-cpython-311/src/pykcs11.o
      clang -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/opt/homebrew/opt/openssl@3/include -Isrc -I/usr/local/include -I/Users/matthewholmes/work/icms/.venv/include -I/Users/matthewholmes/.pyenv/versions/3.11.2/include/python3.11 -c src/pykcs11_wrap.cpp -o build/temp.macosx-13.2-arm64-cpython-311/src/pykcs11_wrap.o
      src/pykcs11_wrap.cpp:5619:3: warning: 'sprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead. [-Wdeprecated-declarations]
                      sprintf(szVal, "%d.%d", self->libraryVersion.major, self->libraryVersion.minor);
                      ^
      /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/stdio.h:180:1: note: 'sprintf' has been explicitly marked deprecated here
      __deprecated_msg("This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead.")
      ^
      /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/cdefs.h:215:48: note: expanded from macro '__deprecated_msg'
              #define __deprecated_msg(_msg) __attribute__((__deprecated__(_msg)))
                                                            ^
      src/pykcs11_wrap.cpp:5630:3: warning: 'sprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead. [-Wdeprecated-declarations]
                      sprintf(szVal, "%d.%02d", self->hardwareVersion.major, self->hardwareVersion.minor);
                      ^
      /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/stdio.h:180:1: note: 'sprintf' has been explicitly marked deprecated here
      __deprecated_msg("This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead.")
      ^
      /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/cdefs.h:215:48: note: expanded from macro '__deprecated_msg'
              #define __deprecated_msg(_msg) __attribute__((__deprecated__(_msg)))
                                                            ^
      src/pykcs11_wrap.cpp:5635:3: warning: 'sprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead. [-Wdeprecated-declarations]
                      sprintf(szVal, "%d.%02d", self->firmwareVersion.major, self->firmwareVersion.minor);
                      ^
      /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/stdio.h:180:1: note: 'sprintf' has been explicitly marked deprecated here
      __deprecated_msg("This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead.")
      ^
      /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/cdefs.h:215:48: note: expanded from macro '__deprecated_msg'
              #define __deprecated_msg(_msg) __attribute__((__deprecated__(_msg)))
                                                            ^
      src/pykcs11_wrap.cpp:5652:3: warning: 'sprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead. [-Wdeprecated-declarations]
                      sprintf(szVal, "%d.%02d", self->firmwareVersion.major, self->firmwareVersion.minor);
                      ^
      /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/stdio.h:180:1: note: 'sprintf' has been explicitly marked deprecated here
      __deprecated_msg("This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead.")
      ^
      /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/cdefs.h:215:48: note: expanded from macro '__deprecated_msg'
              #define __deprecated_msg(_msg) __attribute__((__deprecated__(_msg)))
                                                            ^
      src/pykcs11_wrap.cpp:15849:64: error: use of undeclared identifier 'SWIGTYPE_p_std__vectorT_unsigned_char_std__allocatorT_unsigned_char_t_t'
          if (SWIG_IsOK(SWIG_ConvertPtr(swig_obj[1], (void **)&vect, SWIGTYPE_p_std__vectorT_unsigned_char_std__allocatorT_unsigned_char_t_t, 0)))
                                                                     ^
      src/pykcs11_wrap.cpp:16027:60: error: use of undeclared identifier 'SWIGTYPE_p_std__vectorT_unsigned_char_std__allocatorT_unsigned_char_t_t'
          int res = SWIG_ConvertPtr(swig_obj[1], (void **)&vect, SWIGTYPE_p_std__vectorT_unsigned_char_std__allocatorT_unsigned_char_t_t, 0);
                                                                 ^
      src/pykcs11_wrap.cpp:16145:6 [...]

2024-01-30 12:20 UTC, MattHolmes123 commented on config/env.py
> +
As discussed in slack, please add comments about how to set this up when running locally and remember to update icms/.env.local-docker

2024-01-30 14:36 UTC, MattHolmes123 commented on web/domains/case/tasks.py
> +            file_obj = signer.sign_pdf(file_obj)
This won't sign cover letters, V1 digitally signs all documents.

2024-01-30 14:40 UTC, MattHolmes123 commented on .env.circleci
> +P12_SIGNATURE_PASSWORD='' # Value in Vault
Missing newline at end of file (Can be fixed in pycharm automatically.
Settings -> Editor -> General -> Ensure every saved file ends in a linebreak

2024-01-30 14:43 UTC, MattHolmes123 commented on scripts/initial-setup.sh
> +      /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
I'd rather we warn and exit early than installing homebrew automatically.

2024-01-30 15:00 UTC, MattHolmes123 commented on web/jinja2.py
> +        return base64.b64encode(file.read()).decode("utf-8")  # /PS-IGNORE
No need to manually open with a `Path` instance
`return base64.b64encode(file_path.read_bytes()).decode("utf-8")`

2024-01-30 15:01 UTC, MattHolmes123 commented on web/static/web/css/components/signature.css
> +}
missing new line.

2024-01-30 15:01 UTC, MattHolmes123 commented on web/static/web/css/pdfs/com-certificate-style.css
> +}
missing new line

2024-01-30 15:05 UTC, MattHolmes123 commented on web/static/web/css/pdfs/licence-and-certificate-common-style.css
> +}
missing newline

2024-01-30 15:06 UTC, MattHolmes123 commented on web/templates/pdf/export/com-certificate.html
> +	<head>
No tabs please and 2 spaces to keep consistent with most of the codebase.

2024-01-30 15:09 UTC, MattHolmes123 commented on web/templates/pdf/import/cover-letter.html
> +	      {% for line in ilb_contact_address_split %}
Indentation doesn't match closing `{% endfor %}`

2024-01-30 15:23 UTC, MattHolmes123 commented on web/utils/pdf/generator.py
> +                    return "web/domains/case/import/manage/preview-licence.html"
Textiles isn't a live application, I wonder why this is here... We should probably remove it.

2024-01-30 15:24 UTC, MattHolmes123 commented on web/utils/pdf/generator.py
> +                context = utils.get_licence_context(self.application, self.doc_pack, self.doc_type)
Same here. 
I am not sure why we have textiles listed.
@mikeylockwood can you remember?

2024-01-30 15:33 UTC, MattHolmes123 commented on web/utils/pdf/signer.py
> +        "sigflagsft": 132,
Could this be constants to indicate what these values mean.
Instead of magic numbers.

2024-01-30 15:34 UTC, MattHolmes123 commented on web/utils/pdf/signer.py
> +        "signingdate": date,
No real need for the `date` variable.
`"signingdate": datetime.datetime.utcnow().strftime("D:%Y%m%d%H%M%S+00'00'")`

2024-01-30 15:36 UTC, mikeylockwood commented on web/utils/pdf/generator.py
> +                context = utils.get_licence_context(self.application, self.doc_pack, self.doc_type)
This has been added in this PR. Textiles wasn't listed before

2024-01-30 15:36 UTC, MattHolmes123 commented on web/utils/pdf/signer.py
> +    signed_pdf.seek(0)
We reset the readpoint in the places this function is called, I wonder if we are wise to make assumptions here.

2024-01-30 15:38 UTC, MattHolmes123 requested changes
Added several comments

2024-01-30 15:38 UTC, MattHolmes123 commented on web/utils/pdf/generator.py
> +                context = utils.get_licence_context(self.application, self.doc_pack, self.doc_type)
Cool thanks for clarifying, in that case should remove it.

2024-01-30 16:19 UTC, chris-pettinga commented on .env.circleci
> +P12_SIGNATURE_PASSWORD='' # Value in Vault
@MattHolmes123 thanks for the tip

2024-01-30 16:25 UTC, chris-pettinga commented on web/utils/pdf/signer.py
> +    signed_pdf.seek(0)
I would say better to be safe than sorry? Two `.seek(0)` in a row doesn't have any ill-effect.

2024-01-30 16:29 UTC, MattHolmes123 commented on web/utils/pdf/signer.py
> +    signed_pdf.seek(0)
But doing it here assumes we have finished writing to the BytesIO stream.

2024-01-30 17:19 UTC, chris-pettinga commented on web/static/web/css/pdfs/licence-and-certificate-common-style.css
> +    color: rgb(128, 128, 128);
Great spot, thank you I didn't realise

2024-01-31 08:31 UTC, MattHolmes123 commented on web/static/web/css/pdfs/licence-and-certificate-common-style.css
> +    color: rgb(128, 128, 128);
That was one of the bugs I raised:
https://uktrade.atlassian.net/browse/ICMSLST-2482

2024-01-31 09:23 UTC, mikeylockwood commented on Dockerfile
> +RUN apt-get update && apt-get install wget graphviz libgraphviz-dev gcc libpq-dev swig postgresql-client npm -y
The problem is with `PyKCS11 1.5.13` which was released January 7th. `pip install pykcs11==1.5.12` installs okay and allows you to install endesive

2024-01-31 12:28 UTC, MattHolmes123 commented on Dockerfile
> +RUN apt-get update && apt-get install wget graphviz libgraphviz-dev gcc libpq-dev swig postgresql-client npm -y
Nice one @mikeylockwood This does fix `make setup`

2024-01-31 12:33 UTC, MattHolmes123 commented on web/utils/pdf/signer.py
> +    return signature_image_coordinates, page_number
Couple of points.
- pdf_file has a `pages` method to return an iterable.
- the Page class has a `number` attribute to indicate the page number.
- Although it won't ever really happen this code has a bug in it if the pdf_file is empty. In that instance page_number would be undefined.

Added a version below that resolves all the above and removes the `else` block of the for loop (as they can almost always be written in a better way that's easier to understand).
```
    for page in pdf_file.pages():
        signature_header_text = page.search_for(signature_header_text)
        signature_footer_text = page.search_for(signature_footer_text)

        if signature_footer_text and signature_header_text:
            # Because PyMuPDF uses a different coordinate system to endesive we need to convert
            # between the two.
            # PyMuPDF uses the top left corner as 0,0 and endesive uses the bottom left corner as
            # 0,0
            page_size = page.bound()
            signature_image_coordinates = (
                signature_footer_text_rect.x0,  # type: ignore[attr-defined]
                page_size.y1 - signature_footer_text_rect.y0,  # type: ignore[attr-defined]
                signature_footer_text_rect.x1,  # type: ignore[attr-defined]
                page_size.y1 - signature_header_text_rect.y1,  # type: ignore[attr-defined]
            )

            return signature_image_coordinates, page.number

    raise SignatureTextNotFound("Unable to find signature text in pdf")
```

A snippet highlighting the bug I was referring to:
```
>>> def foo():
...     for x, y in enumerate([]):
...         ...
...     print(x)
...
>>> foo()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 4, in foo
UnboundLocalError: cannot access local variable 'x' where it is not associated with a value
>>>
```

2024-01-31 13:10 UTC, MattHolmes123 commented on web/utils/pdf/signer.py
> +    return signature_image_coordinates, page_number
Actually I'm wrong about the bug... Of course the `else` block will raise before then!
Just highlights my problem that I find them confusing 😄

2024-01-31 13:54 UTC, MattHolmes123 commented on requirements-base.txt
> +pyOpenSSL~=24.0
I would just reorder these slightly to be really explicit about what we are doing:
e.g.
```
playwright~=1.14
pyOpenSSL~=24.0
# Pin endesive sub-dependencies as they aren't pinned in endesive repo
# Periodically review these to see if we can install newer versions
endesive~=2.17.0
pykcs11==1.4.4      # endesive sub-dependency (>=1.5 macOS install bug)
cryptography~=42.0  # endesive sub-dependency
asn1crypto~=1.5     # endesive sub-dependency
oscrypto~=1.3       # endesive sub-dependency
certvalidator~=0.11 # endesive sub-dependency
pillow~=10.2        # endesive sub-dependency
paramiko~=3.4       # endesive sub-dependency
attrs~=23.2         # endesive sub-dependency
```

2024-01-31 13:57 UTC, MattHolmes123 commented on web/templates/pdf/import/sanctions-licence.html
> +      {% endif %}
random formatting

2024-01-31 13:57 UTC, MattHolmes123 commented on web/templates/pdf/import/wood-licence.html
> +    </style>
Random formatting and return of the tabs.

2024-01-31 13:58 UTC, MattHolmes123 commented on web/templates/pdf/shared/fa-licence-base.html
> +  </style>
Same here

2024-01-31 14:01 UTC, MattHolmes123 approved these changes
Added a few final comments. 👍 
I've raised a few bugs so whatever you don't fix here you can do later.

2024-01-31 14:02 UTC, MattHolmes123 commented on requirements-base.txt
> +pyOpenSSL~=24.0
Also do we need pyOpenSSL as a dependency?

2024-01-31 17:38 UTC, chris-pettinga commented on requirements-base.txt
> +pyOpenSSL~=24.0
We use it only for testing purposes to create a mock signing cert, which seems wasteful but creating a pksc12 certificate with the cryptography module is a nightmare. The alternative is to use a fixture to store the base64 but that feels like a waste, + a weird smell to have base64 encoded certificate in the codebase

2024-02-01 09:37 UTC, MattHolmes123 commented on requirements-base.txt
> +pyOpenSSL~=24.0
Fair enough, I only asked as it isn't a subdependency of endesive / imported anywhere in the codebase.
But if it's useful for now thats fine 👍

2024-02-01 17:30 UTC, mikeylockwood approved these changes

2024-02-01 22:21 UTC, merged