ICMSLST-2009 - Issued Certificate Report
uktrade/icms pull request #1297
Opened 2024-01-23 12:40 UTC by marcuspp

2024-01-25 09:04 UTC, marcuspp commented on web/reports/interfaces.py
> +            total_processing_time=self.get_total_processing_time(cdr, export_application),
These values are the same as there was no real understanding of what case processing time is, so therefore ignored. The value seems to be total minus any time taken for an application update. Column could be removed but left in so output is the same as V1 (plus business days)

2024-01-25 10:16 UTC, chris-pettinga requested changes
Some comments but overall looks great! Hell of a lot of code so well done!

2024-01-25 10:16 UTC, chris-pettinga commented on web/reports/views.py
> +class ReportViewMixin(LoginRequiredMixin, PermissionRequiredMixin):
In my mind a Mixin shouldn't inherit from any classes, when it does so it becomes a Base/Abstract class.

2024-01-25 10:16 UTC, chris-pettinga commented on web/reports/views.py
> +        context["page_title"] = "Reports"
can this not be done in the .html template itself? Same for the page_title elements below

2024-01-25 10:16 UTC, chris-pettinga commented on web/reports/views.py
> +        for field, value in form.cleaned_data.items():
I would pop `title` and `notes` manually from the cleaned_data dict so it's more explicit what we don't want to return, rather than loop through and check every time

2024-01-25 10:16 UTC, chris-pettinga commented on web/reports/views.py
> +        context["page_title"] = "Reports"
this only makes sense if I'm correct in thinking that the `page_title` context value maps to the <title> tag on the page. Reason being that anything that is explicitly to do with the appearance of a page should rather be done in the page itself rather than in Python

2024-01-25 10:16 UTC, chris-pettinga commented on web/reports/views.py
> +    def get_report(self) -> Report:
It looks like all views use this, so I would override the __dispatch__ method are assign it the view `self` as an attribute so it doesn't have to be run twice per view, i.e. once in `get_context_data` and again in `form_valid`

2024-01-25 10:16 UTC, chris-pettinga commented on web/reports/models.py
> +            return last_run.finished_at.strftime("%d %b %Y %H:%M:%S")
I think Python functions should always try and return flexible python objects, in this case a date object. If the only reason this is returning a string is so it can be rendered in HTML cleanly, I would move the .strftime to the .HTML file itself. 

This allows you to open up this function to be ran by other python functions which need to operate on a datetime object, rather than converting it back from a string

2024-01-25 10:16 UTC, chris-pettinga commented on web/reports/generate.py
> +    write_files(report_interface)
I would move `write_files` to a method on the `ReportInterface` base_class as it seems like something that the ReportInterface object does to itself, rather than pass it to another function. Not a blocker however just personal preference

2024-01-25 10:16 UTC, chris-pettinga commented on web/reports/generate.py
> +    write_files(report_interface)
Then also you could move all the other sub_functions as methods on the BaseClass, could also help with overriding down the line if we want to implement different saving behaviour for different types of reports

2024-01-25 11:07 UTC, marcuspp commented on web/reports/views.py
> +    def get_report(self) -> Report:
I'm not sure this matters as `get_context_data` will only be called on a GET request or an invalid POST request whereas the call within `form_valid` is called on a valid POST request. So in both cases it should only be called once.

2024-01-25 11:08 UTC, marcuspp commented on requirements-base.txt
> +numpy==1.26.3
Happy to switch packages. Will give it a try and see if it is a drop in replacement

2024-01-25 11:22 UTC, MattHolmes123 requested changes

2024-01-25 11:22 UTC, MattHolmes123 commented on requirements-base.txt
> +numpy==1.26.3
Do we need a package at all:

```
import datetime as dt


def main():
    start = dt.date(year=2020, month=1, day=1)
    end = dt.date(year=2020, month=3, day=31)

    date_diff = end - start
    business_days = 0

    for i in range(date_diff.days + 1):
        day = start + dt.timedelta(days=i)

        # "Return day of the week, where Monday == 0 ... Sunday == 6."
        if day.weekday() < 5:
            business_days += 1

    print(business_days)


if __name__ == "__main__":
    main()
```

2024-01-25 11:22 UTC, MattHolmes123 commented on web/reports/interfaces.py
> +        return numpy.busday_count(submitted_date, completed_date) + 1
```import datetime as dt

    def get_business_days_to_process(
        self, cdr: CaseDocumentReference, export_application: ExportApplication
    ) -> int:

        start = export_application.submit_datetime.date()
        end = cdr.content_object.case_completion_datetime.date()
        date_diff = end - start
        business_days = 0

        for i in range(date_diff.days + 1):
            day = start + dt.timedelta(days=i)

            # "Return day of the week, where Monday == 0 ... Sunday == 6."
            if day.weekday() < 5:
                business_days += 1

        return business_days

```

2024-01-25 11:22 UTC, MattHolmes123 commented on web/reports/serializers.py
> +]
Do you want to link to the jquery form field to indicate why we have to do this.

2024-01-25 11:22 UTC, MattHolmes123 commented on web/reports/views.py
> +class ReportViewMixin(LoginRequiredMixin, PermissionRequiredMixin):
ReportViewBase 👍

2024-01-25 11:57 UTC, marcuspp commented on web/reports/generate.py
> +    write_files(report_interface)
I'm going to leave this as is for now and when i do the next report consider moving them.

2024-01-25 11:59 UTC, marcuspp commented on web/reports/interfaces.py
> +            if not hasattr(export_application, "schedules")
Yeah good shout, i'll update

2024-01-25 12:01 UTC, MattHolmes123 commented on web/reports/interfaces.py
> +        )
This breaks as soon as an application has a variation request.
![image](https://github.com/uktrade/icms/assets/8921101/8cd6e931-a55d-43fd-b8d3-f2ee8df8caa2)
That exampe there shows me running the report twice.
Before the second run I did the following:

1. Create a variation request as an admin worker
2. Created an application update request
3. As the exporter user added two more countries to the app and completed the app update request.
4. Completed the case again as the caseworker
5. reran the report

2024-01-25 12:20 UTC, mikeylockwood commented on web/reports/views.py
> +        context["page_title"] = "Reports"
This is passed in as a context variable as it is set in the base template that the template inherits from

2024-01-25 13:03 UTC, MattHolmes123 commented on web/reports/interfaces.py
> +        )
![image](https://github.com/uktrade/icms/assets/8921101/844fae39-5f57-4197-96ca-f068f243a0ce)

2024-01-29 14:53 UTC, chris-pettinga commented on web/reports/views.py
> +    def get_report(self) -> Report:
@marcuspp this is true, my mistake.

2024-01-29 14:53 UTC, chris-pettinga commented on web/reports/views.py
> +        context["page_title"] = "Reports"
@mikeylockwood makes sense, thank you

2024-01-31 10:01 UTC, chris-pettinga approved these changes

2024-01-31 10:50 UTC, mikeylockwood commented on web/reports/generate.py
> +        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
Maybe mimetypes should be constants in `web/utils/spreadsheet.py`

```
MIMETYPE.XLSX
MIMETYPE.CSV
```

2024-01-31 10:52 UTC, mikeylockwood commented on web/reports/serializers.py
> +]
I think it's clear that it's serilaising datetime objects to strings. What else needs to be known?

2024-01-31 11:03 UTC, MattHolmes123 commented on web/reports/serializers.py
> +]
I believe he created the CustomDateTime because the format is different to how pydantic serialises datetime by default.
`icms/web/forms/fields.py -> JqueryDateField`

```
# Always match the format here: web/static/web/js/fox/core-footer.js
# dateFormat: "dd'-'M'-'yy"
JQUERY_DATE_FORMAT = "%d-%b-%Y"


class JqueryDateField(forms.DateField):
    widget = DateInput(format=JQUERY_DATE_FORMAT)
    input_formats = [JQUERY_DATE_FORMAT]
```

2024-01-31 11:05 UTC, MattHolmes123 commented on web/reports/serializers.py
> +]
It's nothing to do with our JQuery form field :D 
My bad

2024-01-31 12:04 UTC, MattHolmes123 commented on web/reports/interfaces.py
> +        )
Will be fixed in https://uktrade.atlassian.net/browse/ICMSLST-2474

2024-01-31 12:06 UTC, MattHolmes123 approved these changes

2024-01-31 12:25 UTC, marcuspp commented on web/reports/generate.py
> +        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
Yes good shout, i'll do this and then rebase

2024-01-31 13:14 UTC, mikeylockwood approved these changes

2024-01-31 13:32 UTC, merged