ICMSLST-2010 - Import Licence Report
uktrade/icms pull request #1327
Opened 2024-02-12 15:36 UTC by marcuspp

2024-02-20 11:24 UTC, MattHolmes123 commented on web/reports/interfaces.py
> +            ),
Nice!

2024-02-20 12:02 UTC, marcuspp commented on web/reports/interfaces.py
> +            .order_by("-reference", "-variation_no")
The ordering is copied from V1 and `variation_no` is populated in historical applications.

2024-02-20 13:11 UTC, MattHolmes123 commented on web/reports/interfaces.py
> +            .order_by("-reference", "-variation_no")
the reference contains the variation number in it though right?
e.g.
`IMA/2024/00001/1`
what does `variation_no` add?

2024-02-20 16:20 UTC, mikeylockwood commented on web/reports/interfaces.py
> +            .order_by("-reference", "-variation_no")
`reference` is already unique and contains the `variation_no`

2024-02-20 16:23 UTC, mikeylockwood commented on web/reports/interfaces.py
> +        licences = ia.licences.exclude(status=ImportApplicationLicence.Status.DRAFT)
Should `ARCHIVED` also be excluded?

2024-02-20 16:27 UTC, mikeylockwood commented on web/reports/interfaces.py
> +        doc_pack = latest_licence.document_references.filter(document_type="LICENCE").first()
I think there should only be one licence doc on the doc pack so `latest_licence.document_references.get(document_type="LICENCE")` should work

2024-02-20 16:29 UTC, mikeylockwood commented on web/reports/interfaces.py
> +        for goods in ia.sanctions_goods.all().order_by("-commodity"):
This also works without the `.all()`

2024-02-21 11:08 UTC, marcuspp commented on web/reports/interfaces.py
> +            .order_by("-reference", "-variation_no")
Oh got you. I'll remove 👍

2024-02-21 11:23 UTC, MattHolmes123 commented on web/reports/interfaces.py
> +        for goods in ia.sanctions_goods.all().order_by("-commodity"):
I do it more for readability :) 
But you've been telling me to remove `.all()` for years at this point :D

2024-02-22 15:49 UTC, marcuspp commented on web/reports/interfaces.py
> +            sub_type = f"{ia.application_type.type}1"
Left blank

2024-02-23 11:10 UTC, MattHolmes123 requested changes

2024-02-23 11:10 UTC, MattHolmes123 commented on web/reports/interfaces.py
> +            under_appeal="",  # Unused field in V1
We never implemented the under_appeal feature as like you've said it's not used in V1.
Might as well delete it

2024-02-23 11:10 UTC, MattHolmes123 commented on web/reports/interfaces.py
> +            variation_number=ia.variation_no,
I would rather we use V2 logic to work this out instead of a field we don't use anywhere in V2.
e.g. split the reference on `/` and work out if it's a variation.

2024-02-23 11:10 UTC, MattHolmes123 commented on web/reports/models.py
> +        )
I don't see this used anywhere?

2024-02-26 09:18 UTC, marcuspp commented on web/reports/models.py
> +        )
Yes sorry i'll remove

2024-02-26 11:11 UTC, marcuspp commented on web/reports/interfaces.py
> +            licences = ia.licences.exclude(status__in=[ImportApplicationLicence.Status.DRAFT])
`pack_licence_history` doesn't include archived applications so they are different

2024-02-26 11:15 UTC, marcuspp commented on web/reports/interfaces.py
> +            under_appeal="",  # Unused field in V1
I want the report to be same as V1 for easy comparison this column appears in the middle of the file. This could be an improvement after go live. (Where all fields in all reports should be reviewed).

2024-02-26 13:02 UTC, MattHolmes123 commented on web/reports/interfaces.py
> +            licences = ia.licences.exclude(status__in=[ImportApplicationLicence.Status.DRAFT])
It does include Archived licences that were once live:
Here is an example where I created an application and then completed a variation request.
![image](https://github.com/uktrade/icms/assets/8921101/37170c23-b7aa-4b69-9b0e-b2e297a82079)

2024-02-26 13:05 UTC, MattHolmes123 commented on web/reports/interfaces.py
> +            licences = ia.licences.exclude(status__in=[ImportApplicationLicence.Status.DRAFT])
The `pack_licence_history` code doesn't filter on status, it uses the case_reference field as thats what gets set when an application is marked as live:
![image](https://github.com/uktrade/icms/assets/8921101/603237d6-ae11-4700-93c5-9611a5a3e0bf)

Your code will include licences that are archived that I can't imagine we'd care about:
![image](https://github.com/uktrade/icms/assets/8921101/c998655b-d4ab-4ab4-a4d6-915d006f890b)

2024-02-26 13:16 UTC, MattHolmes123 commented on web/reports/interfaces.py
> +            under_appeal="",  # Unused field in V1
Fair enough, if you know the place you could just remove the column from your comparison code though.
But leave it in if it makes your life easier.

2024-02-26 13:18 UTC, MattHolmes123 commented on web/reports/interfaces.py
> +            licences = ia.licences.exclude(status__in=[ImportApplicationLicence.Status.DRAFT])
Unless we do care about everything that is :)

2024-02-26 13:24 UTC, MattHolmes123 approved these changes

2024-02-26 15:43 UTC, merged