ICMSLST-2524 - Adding google analytics support
uktrade/icms pull request #1347
Opened 2024-02-22 16:32 UTC by chris-pettinga

Added support for google analytics, tags are dynamically created and injected into the base.html at render-time

Added a rough-and-ready cookie consent page for users to manage their cookie preferences:
<img width="937" alt="image" src="https://github.com/uktrade/icms/assets/23667847/c62a60fa-5ca6-480b-a793-9c598bf80cac">

<img width="995" alt="image" src="https://github.com/uktrade/icms/assets/23667847/b475e985-b846-46be-b2e1-72374b63ebbb">

2024-02-22 16:34 UTC, chris-pettinga commented
Will make sure to add the necessary env vars to vault before merge.

@MattHolmes123 I will also liaise with Lawrence to make sure they get added to DBT Platform.

2024-02-22 16:40 UTC, mikeylockwood commented on .env.local-docker
> +GTM_EXPORTER_PREVIEW_KEY=''
Do we need this to be separate for each domian? Analytics can surely filter by domain in the results

2024-02-22 16:46 UTC, mikeylockwood commented on web/templates/base.html
> +	<!-- Google Tag Manager -->
What are we doing about consent? We will be legally required to ask for consent for analytics. GTM should be run with consent mode and send an update after consent is provided
https://support.google.com/google-ads/answer/10000067

2024-02-23 08:22 UTC, MattHolmes123 commented on web/tests/organisations.py
> +from .type_classes import (
We have loads of files called `types.py` when were you getting an import error?

2024-02-23 08:42 UTC, MattHolmes123 commented
> Will make sure to add the necessary env vars to vault before merge.
> 
> @MattHolmes123 I will also liaise with Lawrence to make sure they get added to DBT Platform.

@chris-pettinga what about the GA login details? Are you adding them to Passman?

2024-02-23 08:54 UTC, MattHolmes123 requested changes

2024-02-23 08:54 UTC, MattHolmes123 commented on config/settings.py
> +    "Import A Licence": env.gtm_exporter_auth_key,
Keys don't match env values.

2024-02-23 08:54 UTC, MattHolmes123 commented on config/settings.py
> +    "Import A Licence": env.gtm_exporter_container_id,
Keys don't match env values.

2024-02-23 08:54 UTC, MattHolmes123 commented on config/settings.py
> +    "Import A Licence": env.gtm_exporter_preview_key,
Keys don't match env values.

2024-02-23 08:54 UTC, MattHolmes123 commented on web/jinja2.py
> +    return settings.GTM_PREVIEW_KEYS[current_site.name]
All calls to `current_site = get_current_site(request)` can be replaced by `request.site`
https://docs.djangoproject.com/en/5.0/ref/middleware/#django.contrib.sites.middleware.CurrentSiteMiddleware

2024-02-23 08:54 UTC, MattHolmes123 commented on config/settings.py
> +GTM_AUTH_KEYS = {
Use `{SiteName.CASEWORKER: env.XXX, SiteName.EXPORTER: env.XXX, SiteName.IMPORTER: env.XXX}` instead of strings in all three dicts.

2024-02-23 08:54 UTC, MattHolmes123 commented on web/jinja2.py
> +    return settings.GTM_PREVIEW_KEYS[current_site.name]
If you look in `web/types.py` we have a type for an authenticated http request:

```python
class AuthenticatedHttpRequest(HttpRequest):
    user: "User"
    icms: "ICMSMiddlewareContext"
    site: "Site"
```

Add missing types to each function definition.

2024-02-23 08:54 UTC, MattHolmes123 commented on web/tests/organisations.py
> +from .type_classes import (
I've checked out the branch and renamed it back to types.py and everything works?
![image](https://github.com/uktrade/icms/assets/8921101/dc850f4d-5719-463c-9b47-945c8745f7e8)

2024-02-23 08:54 UTC, MattHolmes123 commented on web/tests/organisations.py
> +from .type_classes import (
Change this back if you can please

2024-02-23 08:54 UTC, MattHolmes123 commented on web/tests/test_templatetags/test_gtm_tags.py
> +from django.conf import settings
We are testing functionality in `web/jinja2.py` so i'd prefer we match the project structure like the most of the tests do.
e.g. `web/tests/test_jinja2.py`

Also jinja doesn't have templatetags it has filters and global functions.

2024-02-23 08:54 UTC, MattHolmes123 commented on web/tests/test_templatetags/test_gtm_tags.py
> +    assert set(settings.GTM_PREVIEW_KEYS.keys()) == {each[0] for each in SiteName.choices}
TextChoice has a labels property
```
>>> from web.sites import SiteName
>>> SiteName.labels
['Caseworker', 'Export A Certificate', 'Import A Licence']
>>> 
```

2024-02-23 09:53 UTC, chris-pettinga commented on web/tests/organisations.py
> +from .type_classes import (
I'm getting the below with the file named `types.py`:

`ImportError: cannot import name 'MappingProxyType' from partially initialized module 'types' (most likely due to a circular import) (/...icms/web/tests/types.py)`

The more I look into this however, it looks like a PyCharm issue and something to do with SOURCES_ROOT being included in the Python PATH

2024-02-23 09:54 UTC, chris-pettinga commented on config/settings.py
> +    "Import A Licence": env.gtm_exporter_auth_key,
stupid mistake, fixed.

2024-02-23 09:54 UTC, chris-pettinga commented on config/settings.py
> +    "Import A Licence": env.gtm_exporter_container_id,
stupid mistake, fixed.

2024-02-23 09:54 UTC, chris-pettinga commented on config/settings.py
> +    "Import A Licence": env.gtm_exporter_preview_key,
stupid mistake, fixed.

2024-02-23 09:56 UTC, chris-pettinga commented on web/jinja2.py
> +    return settings.GTM_PREVIEW_KEYS[current_site.name]
don't you mean `web/type_classes.py` 😂

2024-02-23 09:56 UTC, chris-pettinga commented on web/jinja2.py
> +    return settings.GTM_PREVIEW_KEYS[current_site.name]
fixed, thank you.

2024-02-23 09:57 UTC, chris-pettinga commented on config/settings.py
> +GTM_AUTH_KEYS = {
This results in a circular import as the SiteName type class also important django.conf.settings

2024-02-23 10:01 UTC, chris-pettinga commented on .env.local-docker
> +GTM_EXPORTER_PREVIEW_KEY=''
The analytics team requested that we have separate containers for each Site as they're different websites (at least according to the user) and used by completely different people.

2024-02-23 10:02 UTC, chris-pettinga commented on web/tests/test_templatetags/test_gtm_tags.py
> +    assert set(settings.GTM_PREVIEW_KEYS.keys()) == {each[0] for each in SiteName.choices}
good info, thank you.

2024-02-23 10:45 UTC, chris-pettinga commented on config/settings.py
> +GTM_AUTH_KEYS = {
This is also why I added the test to ensure that the dictionary keys match the actual SiteName attributes

2024-02-23 11:02 UTC, chris-pettinga commented on web/templates/base.html
> +	<!-- Google Tag Manager -->
How did I forget about consent, must not be all here this week

2024-02-23 11:03 UTC, chris-pettinga commented on web/templates/base.html
> +	<!-- Google Tag Manager -->
Is this perhaps a final task for Manuel/Karwai or will that drag this out too long when I can whip up a functional albeit ugly one. Will speak to Dan.

2024-02-23 11:04 UTC, chris-pettinga commented
> > Will make sure to add the necessary env vars to vault before merge.
> > @MattHolmes123 I will also liaise with Lawrence to make sure they get added to DBT Platform.
> 
> @chris-pettinga what about the GA login details? Are you adding them to Passman?

I can do, however I think the end goal is for the analytics team to create a dashboard on data workspace that will make the data gathered a lot easier to digest

2024-02-23 11:13 UTC, MattHolmes123 commented on config/settings.py
> +GTM_AUTH_KEYS = {
Ahh fair enough.

2024-02-23 11:15 UTC, MattHolmes123 commented on web/tests/organisations.py
> +from .type_classes import (
I don't get that error in pycharm 🤔

2024-02-23 11:18 UTC, MattHolmes123 commented on config/settings.py
> +GTM_AUTH_KEYS = {
You could move everything to env and have it return a dict, but it's not that important.

2024-02-23 11:20 UTC, MattHolmes123 commented
> > > Will make sure to add the necessary env vars to vault before merge.
> > > @MattHolmes123 I will also liaise with Lawrence to make sure they get added to DBT Platform.
> > 
> > 
> > @chris-pettinga what about the GA login details? Are you adding them to Passman?
> 
> I can do, however I think the end goal is for the analytics team to create a dashboard on data workspace that will make the data gathered a lot easier to digest

It's just so that I could test it in future if you weren't here.
There is nothing to say the datails have to be the same for prod and non prod right?

2024-02-26 14:30 UTC, MattHolmes123 commented on web/templates/web/cookie-consent.html
> +        <p>We use cookies to make ICMS work and collect information about how you use our service.</p>
ICMS is an internal name for the service. It should be `{{ request.site.name }}`

2024-02-26 14:30 UTC, MattHolmes123 commented on web/templates/web/cookie-consent.html
> +        <p>Essential cookies keep your information secure while you use Notify. We do not need to ask permission to use
`Notify` -> `{{ request.site.name }}`

2024-02-26 14:31 UTC, MattHolmes123 commented on web/templates/web/cookie-consent.html
> +        <p>We use cookies to make ICMS work and collect information about how you use our service.</p>
Same comment for all references to ICMS on this page.

2024-02-26 14:35 UTC, MattHolmes123 commented on web/views/views.py
> +            cookie_max_age = 365 * 24 * 60 * 60
In the template you've said it lasts 2 years

2024-02-26 14:51 UTC, chris-pettinga commented on web/views/views.py
> +            cookie_max_age = 365 * 24 * 60 * 60
the GA preferences cookie lasts for 1 year, the google analytics cookies themselves (_ga and _gid) last for 2 years

2024-02-27 08:18 UTC, MattHolmes123 commented on web/templates/base.html
> +    })(window, document, 'script', 'dataLayer', '{{ get_gtm_container_id(request) }}');</script>
I would have left this minified if it's something you copy & paste from the google tag manager site.

2024-02-27 08:20 UTC, MattHolmes123 commented on web/templates/base.html
> +        <div class="cookie-banner" data-nosnippet role="region" aria-label="Cookies on ICMS">
Site name not icms

2024-02-27 08:20 UTC, MattHolmes123 commented on web/templates/base.html
> +                Cookies on ICMS
Site name not ICMS

2024-02-27 08:21 UTC, MattHolmes123 commented on web/templates/layout/public.html
> +	      <a href="{{ icms_url('cookie-consent') }}?referrer_url={{ request.path }}">Cookies</a>
Tabs and spaces.

2024-02-27 08:22 UTC, MattHolmes123 commented on web/templates/web/cookie-consent.html
> +        <p>With your permission, we use Google Analytics to collect data about how you use Notify. This information
Site name not Notify

2024-02-27 08:28 UTC, mikeylockwood commented on web/templates/base.html
> +    <!-- Google Tag Manager -->
GTM would still need to be set up with consent mode enabled

```
// if not consent cookie
  window.dataLayer = window.dataLayer || [];
  function gtag() {dataLayer.push(arguments);}
  gtag('consent', 'default', {
    'ad_storage': 'denied',
    'analytics_storage': 'denied',
    'ad_user_data': 'denied',
    'ad_personalization': 'denied',
    'personalization_storage': 'denied',
    'functionality_storage': 'denied',
    'security_storage': 'denied',
  });
// else send the consent options stored in the consent cookie
  gtag('consent', 'default', consent_options)

2024-02-27 08:31 UTC, MattHolmes123 commented on web/views/views.py
> +                initial_dict["accept_cookies"] = False
I wonder if we really need any of this?
If they've already accepted I doubt they will ever come back to this page.

2024-02-27 08:38 UTC, mikeylockwood commented on web/views/views.py
> +                initial_dict["accept_cookies"] = False
they need to be able to update their consent choices in future to be compliant

2024-02-27 08:42 UTC, chris-pettinga commented on web/templates/base.html
> +    })(window, document, 'script', 'dataLayer', '{{ get_gtm_container_id(request) }}');</script>
This is what the Monitoring & Analytics teams have sent me as a copy-paste code snippet

2024-02-27 08:50 UTC, MattHolmes123 commented on web/views/views.py
> +                initial_dict["accept_cookies"] = False
They still can, this is just setting a value to yes or no.

2024-02-27 08:54 UTC, MattHolmes123 commented on web/views/views.py
> +                initial_dict["accept_cookies"] = False
I'm just weary of this `ast.literal_eval`
https://docs.python.org/3/library/ast.html#ast.literal_eval
 _A relatively small input can lead to memory exhaustion or to C stack exhaustion, crashing the process. There is also the possibility for excessive CPU consumption denial of service on some inputs. Calling it on untrusted data is thus not recommended._

2024-02-27 08:59 UTC, mikeylockwood commented on web/views/views.py
> +                initial_dict["accept_cookies"] = False
Oh I see, so whether it retains the previous selection or not? I would keep it but change the if / elif to. `false` should be the default option anyway if nothing is selected
```initial_dict["accept_cookies"] = ga_cookies_accepted == "true"```

2024-02-27 09:24 UTC, mikeylockwood commented on web/views/views.py
> +                initial_dict["accept_cookies"] = False
`json.loads()` might be a better option than `ast.literal_eval()` but may need to be tested with bad cookie strings and maybe a `try/except`

2024-02-27 10:55 UTC, MattHolmes123 commented on web/views/views.py
> +def cookie_consent_view(request):
Missing types and can we have a comment that links to the readme as that would have been useful when reviewing / for future reference

2024-02-28 09:45 UTC, mikeylockwood approved these changes

2024-02-28 11:05 UTC, MattHolmes123 commented on web/views/views.py
> +            if not url_has_allowed_host_and_scheme(referrer_url, settings.ALLOWED_HOSTS):
When I did this in the one login code I included the `require_https` arg
```
if next_url and url_has_allowed_host_and_scheme(
        next_url, allowed_hosts=settings.ALLOWED_HOSTS, require_https=request.is_secure()
    )
```

2024-02-28 11:06 UTC, MattHolmes123 approved these changes

2024-02-29 10:40 UTC, merged