ICMSLST-1354 - SIIL Firearms Report - Include missing Upload Document option.
uktrade/icms pull request #1435
Opened 2024-04-08 13:23 UTC by chris-pettinga

Before:
![image](https://github.com/uktrade/icms/assets/23667847/9bac9fbe-eb15-4619-ad0e-867b47690a35)

After:
![image](https://github.com/uktrade/icms/assets/23667847/a316d72d-a202-40ff-9222-c0511a0bdfdc)

2024-04-08 13:57 UTC, MattHolmes123 commented on web/domains/case/_import/fa_sil/types.py
> +        forms.SILSupplementaryReportUploadFirearmSection2Form,
You can define unions with `|`
```
SILReportUploadFirearmFormT = type[
        forms.SILSupplementaryReportUploadFirearmSection1Form
        | forms.SILSupplementaryReportUploadFirearmSection2Form
        | forms.SILSupplementaryReportUploadFirearmSection5Form
        | forms.SILSupplementaryReportUploadFirearmSection582ObsoleteForm  # /PS-IGNORE
        | forms.SILSupplementaryReportUploadFirearmSection582OtherForm  # /PS-IGNORE
        | forms.SILSupplementaryReportUploadFirearmSectionLegacyForm
```

2024-04-08 13:59 UTC, MattHolmes123 commented on web/domains/case/_import/fa_sil/views.py
> +    raise NotImplementedError(f"sil_section_type is not supported: {sil_section_type}")
Does it not format very nicely when using a `match` statement?

2024-04-08 14:05 UTC, MattHolmes123 commented on web/domains/case/_import/fa_sil/views.py
> +    application: models.SILApplication = get_object_or_404(models.SILApplication, pk=application_pk)
Do we need any permission checking (the same as the upload document view)?

2024-04-08 14:13 UTC, mikeylockwood commented on web/domains/case/_import/fa_sil/views.py
> +    raise NotImplementedError(f"sil_section_type is not supported: {sil_section_type}")
I guess it was s copy of the rest of the code which predates `match` statements

2024-04-08 14:34 UTC, MattHolmes123 requested changes
Needs the permission checking code.

2024-04-08 15:43 UTC, chris-pettinga commented on web/domains/case/_import/fa_sil/views.py
> +    application: models.SILApplication = get_object_or_404(models.SILApplication, pk=application_pk)
Copied it from the other view_upload_document methods, the permissions checking is done in the return function - `view_application_file`:

![image](https://github.com/uktrade/icms/assets/23667847/9267f96b-4570-4246-9a76-4f850dbd358f)

2024-04-09 07:38 UTC, MattHolmes123 commented on web/domains/case/_import/fa_sil/views.py
> +    application: models.SILApplication = get_object_or_404(models.SILApplication, pk=application_pk)
I knew this... :D

2024-04-09 08:07 UTC, chris-pettinga commented on web/domains/case/_import/fa_sil/views.py
> +    application: models.SILApplication = get_object_or_404(models.SILApplication, pk=application_pk)
@MattHolmes123  Happy to approve?

2024-04-09 08:10 UTC, MattHolmes123 commented on web/domains/case/_import/fa_sil/forms.py
> +        fields = ("file",)
Slighty wild idea to replace all these forms as well as the other `_get_report_upload_firearm_form_class` that simply returns one of the above based on a string.

```python
from django import forms
from django.forms import modelform_factory


def get_report_upload_firearm_form(sil_section_type) -> type[forms.ModelForm]:
    match sil_section_type:
        case "section1":
            model_cls = models.SILSupplementaryReportFirearmSection1
        case "section2":
            model_cls = models.SILSupplementaryReportFirearmSection2
        case "section5":
            model_cls = models.SILSupplementaryReportFirearmSection5
        case "section582-obsolete":
            model_cls = models.SILSupplementaryReportFirearmSection582Obsolete
        case "section582-other":
            model_cls = models.SILSupplementaryReportFirearmSection582Other
        case "section_legacy":
            model_cls = models.SILSupplementaryReportFirearmSectionLegacy
        case _:
            raise NotImplementedError(f"sil_section_type is not supported: {sil_section_type}")

    class FileForm(forms.ModelForm):
        document = ICMSFileField(required=True)

    upload_firearms_form = modelform_factory(model_cls, form=FileForm, fields=["document"])

    return upload_firearms_form
```

2024-04-09 08:19 UTC, mikeylockwood commented on web/domains/case/_import/fa_sil/forms.py
> +        fields = ("file",)
Nice, yeah the same could be done for the ReportFirearm forms for manually entering the data. Should change both if you're going to change one. Also be wary of changing the field name from `file` to `document`. There might be shared templates that are also using forms that expect the field to be `file` so would have to also be changed in DFL and OIL as well

2024-04-09 08:20 UTC, MattHolmes123 commented on web/domains/case/_import/fa_sil/forms.py
> +        fields = ("file",)
I just did the example using the name of the model field.

2024-04-09 08:25 UTC, MattHolmes123 approved these changes
approved. 
Happy to go with whatever you decide with the forms.

2024-04-09 08:57 UTC, MattHolmes123 commented on web/domains/case/_import/fa_sil/utils.py
> +        form=django_forms.ModelForm,
You don't need to specify a start form if you aren't doing anything fancy.
A model_class and fields list is enough.

2024-04-09 08:59 UTC, mikeylockwood commented on web/domains/case/_import/fa_sil/utils.py
> +            fields = ("file")
Mismatch field name in the docstring to field name in the form

2024-04-09 09:11 UTC, chris-pettinga commented on web/domains/case/_import/fa_sil/utils.py
> +            fields = ("file")
@mikeylockwood - yes good spot

2024-04-09 09:14 UTC, chris-pettinga commented on web/domains/case/_import/fa_sil/forms.py
> +        fields = ("file",)
There is an odd discrepancy between the form's field name and the attribute on the model, form calls it `file` but the model calls it `document`, I wonder if that's because the upload views use the `create_file_model` function to actually save the file, then assign it to the supp. report:

![image](https://github.com/uktrade/icms/assets/23667847/e1e3d6fe-4c83-4feb-87bc-773b742cd095)

Going to leave the discrepancy for now and update the _get_report_upload_firearm_form_class method for now.

2024-04-09 11:02 UTC, merged