ICMSLST-2525 - User Reactivate/Deactivate emails
uktrade/icms pull request #1482
Opened 2024-04-23 13:16 UTC by marcuspp

2024-04-24 08:42 UTC, MattHolmes123 commented on web/domains/template/context.py
> +                    return "Apply for an export certificate"
The service names are defined here:
```
class SiteName(TypedTextChoices):
    CASEWORKER = (
        "Manage import licences and export certificates",
        "Manage import licences and export certificates",
    )
    EXPORTER = ("Apply for an export certificate", "Apply for an export certificate")
    IMPORTER = ("Apply for an import licence", "Apply for an import licence")

```

2024-04-24 08:44 UTC, MattHolmes123 commented on web/domains/template/context.py
> +                    return "Import licence / export certificate"
You should ideally ask Sally what to call both services together.
e.g.
Apply for an import licence or export certificate

2024-04-24 08:47 UTC, MattHolmes123 commented on web/domains/template/context.py
> +                    return "Import licence / export certificate"
`if is_exporter == is_importer:` will also match where both are False, is this what you want?

2024-04-24 08:48 UTC, marcuspp commented on web/domains/template/context.py
> +                    return "Import licence / export certificate"
It is

2024-04-24 08:48 UTC, marcuspp commented on web/domains/template/context.py
> +                    return "Import licence / export certificate"
We have discussed this and we thought having Apply for an ... infront would make it too long when followed by `account deactivated`

2024-04-24 08:56 UTC, MattHolmes123 commented on web/domains/template/context.py
> +                raise ValueError(f"{item} is not a valid user management template context value")
Alternative using only match and the SiteName labels:
```python
class UserManagementContext:
    def __getitem__(self, item: str) -> str:
        is_importer = self.user.is_importer_user
        is_exporter = self.user.is_exporter_user

        match item, is_importer, is_exporter:
            case "PLATFORM", True, False:
                return SiteName.IMPORTER.label
            case "PLATFORM", False, True:
                return SiteName.EXPORTER.label
            case "PLATFORM", _, _:
                return "Import licence / export certificate"
            case "PLATFORM_LINK", True, False:
                return get_importer_site_domain()
            case "PLATFORM_LINK", False, True:
                return get_exporter_site_domain()
            case "PLATFORM_LINK", _, _:
                return f"{get_importer_site_domain()} for import or {get_exporter_site_domain()} for export."
            case "CASE_OFFICER_EMAIL", _, _:
                return settings.ILB_CONTACT_EMAIL
            case _, _, _:
                raise ValueError(f"{item} is not a valid user management template context value")
```

2024-04-24 08:59 UTC, MattHolmes123 commented on web/domains/user/models.py
> +        return self.exporter_last_login is not None
I wonder if these will be useful elsewhere when you could just as easily use the db columns directly.
I lean towards thin models wherever possible and refactor later when required.

2024-04-24 09:00 UTC, MattHolmes123 commented on web/domains/user/views.py
> +REACTIVATE = "reactivate"
Earlier on you reference these values:
`choices=[("deactivate", "Deactivate User"), ("reactivate", "Reactivate User")],`
I smell a TypedTextChoice coming along :)

2024-04-24 09:00 UTC, MattHolmes123 commented on web/domains/user/views.py
> +    from django.db import QuerySet
No need for TYPE_CHECKING this

2024-04-24 09:01 UTC, MattHolmes123 commented on web/domains/user/views.py
> +
We should refactor this and reference a a constant instead of 0.
```
def get_anonymous_user_instance(user_model: type[User]) -> User:
    # Change the guardian anonymous user pk to match V1 guest user
    kwargs = {
        "pk": 0,
        user_model.USERNAME_FIELD: guardian_settings.ANONYMOUS_USER_NAME,
    }
    user = user_model(**kwargs)
    user.set_unusable_password()

    return user

```

2024-04-24 09:02 UTC, MattHolmes123 commented on web/domains/user/views.py
> +
`ANONYMOUS_USER_PK` ?

2024-04-24 09:03 UTC, MattHolmes123 commented on web/domains/user/views.py
> +        } | context
Elsewhere we do this:
```
return context | {"extra": "context}
```

2024-04-24 09:12 UTC, MattHolmes123 commented on web/domains/template/context.py
> +                    return "Import licence / export certificate"
It's the service name at the end of the day.

2024-04-24 09:17 UTC, MattHolmes123 commented on web/domains/user/views.py
> +class UserDetailView(PermissionRequiredMixin, FormView):
I'm not sure we've done this quite right.
I think the DetailView should remain readonly and we have two new views.
`class ActiveUserFormView`
`class DeactivateUserFormView`
Then the deactive / reactive links would instead take you to the new forms instead of being post only actions

2024-04-24 09:19 UTC, MattHolmes123 commented on web/domains/user/views.py
> +class UserDetailView(PermissionRequiredMixin, FormView):
Would result in cleaner views that only do one thing, I imagine there could be a base class for both new views.

2024-04-24 09:22 UTC, MattHolmes123 requested changes
I think we should split the views

2024-04-25 07:43 UTC, MattHolmes123 commented on web/domains/template/context.py
> +                raise ValueError(f"{item} is not a valid user management template context value")
@marcuspp This fixes  mypy:
```
class UserManagementContext:
    def __init__(self, user: User) -> None:
        self.user = user

    def __getitem__(self, item: str) -> str:
        is_importer = self.user.is_importer_user
        is_exporter = self.user.is_exporter_user

        match item, is_importer, is_exporter:
            case "PLATFORM", True, False:
                return SiteName.IMPORTER.label
            case "PLATFORM", False, True:
                return SiteName.EXPORTER.label
            case "PLATFORM", _, _:
                return PLATFORM_NAME
            case "PLATFORM_LINK", True, False:
                return get_importer_site_domain()
            case "PLATFORM_LINK", False, True:
                return get_exporter_site_domain()
            case "PLATFORM_LINK", _, _:
                return f"{get_importer_site_domain()} for import or {get_exporter_site_domain()} for export."
            case "CASE_OFFICER_EMAIL", _, _:
                return settings.ILB_CONTACT_EMAIL

        raise ValueError(f"{item} is not a valid user management template context value")
```

2024-04-25 07:46 UTC, MattHolmes123 commented on web/domains/user/actions.py
> +class ActivateUser(LinkAction):
Can we add types for all methods of `ActivateUser` and `DeactivateUser`

2024-04-25 07:47 UTC, MattHolmes123 commented on web/domains/user/forms.py
> +        fields = ["subject", "body", "send_email", "action"]
`"action"`doesn't have a field defined, that right?

2024-04-25 07:48 UTC, MattHolmes123 commented on web/domains/user/forms.py
> +        fields = ["subject", "body", "send_email", "action"]
Actually... its a Form not a model form so we can remove this:
```
    class Meta:
        fields = ["subject", "body", "send_email", "action"]
```

2024-04-25 07:57 UTC, MattHolmes123 commented on web/domains/user/views.py
> +    def get_queryset(self) -> "QuerySet[User]":
`"QuerySet[User]"` -> QuerySet[User]

2024-04-25 08:13 UTC, MattHolmes123 commented on web/templates/web/domains/user/detail.html
> +{% endblock %}
Missing newline

2024-04-25 08:13 UTC, MattHolmes123 commented on web/templates/web/domains/user/user_management.html
> +{% endblock  %}
Same

2024-04-25 08:18 UTC, MattHolmes123 commented on web/domains/user/views.py
> +        return get_object_or_404(User, ~Q(is_superuser=True, pk=ANONYMOUS_USER_PK), pk=pk)
The user list view and the two places you do this you could potentially use a reusable function to get you most of the way:
```
def user_list_view_qs() -> QuerySet[User]:
    """Reusable QuerySet that can be used in several views."""
    return User.objects.exclude(pk=ANONYMOUS_USER_PK).exclude(is_superuser=True)
```

2024-04-25 08:20 UTC, MattHolmes123 commented on web/domains/user/views.py
> +        )
Also SingleObjectMixin supports `queryset`, so if you went with that reusable function above you wouldn't need to reimplement what SingleObjectMixin is good at.

2024-04-25 09:10 UTC, MattHolmes123 approved these changes

2024-04-25 10:04 UTC, merged