ICMSLST-1822 - All applications - Further Information request the from ILB cases prompts decision action to release ownership
uktrade/icms pull request #1509
Opened 2024-05-02 15:01 UTC by chris-pettinga

After:
![image](https://github.com/uktrade/icms/assets/23667847/4a902027-9a43-47d6-a876-ec997383dbd1)

2024-05-09 15:21 UTC, MattHolmes123 commented on web/domains/case/views/views_fir.py
> +from ..access.models import AccessRequest
Full import path please if you are doing `..`

2024-05-09 15:21 UTC, MattHolmes123 commented on web/domains/case/views/views_fir.py
> +from ..access.models import AccessRequest
Actually, this is a model import so `from web.models import AccessRequest`

2024-05-09 15:38 UTC, mikeylockwood commented on web/domains/case/views/utils.py
> +        application.status = model_class.Statuses.SUBMITTED
Are the only status's this would be in `PROCESSING` and `VARIATION_REQUESTED`. Prefer to check the `True` condition rather than the `not False` condition
```
if application.status != model_class.Statuses.PROCESSING:
```

2024-05-09 15:38 UTC, mikeylockwood commented on web/domains/case/views/utils.py
> +def release_ownership_of_application(application: ImpOrExp, model_class: ImpOrExpT) -> ImpOrExp:
Is this just for applications or access requests too?

2024-05-09 15:39 UTC, mikeylockwood commented on web/domains/case/views/utils.py
> +def release_ownership_of_application(application: ImpOrExp, model_class: ImpOrExpT) -> ImpOrExp:
I can see below access requests are explicitly excluded

2024-05-09 15:45 UTC, mikeylockwood commented on web/templates/web/domains/case/manage/edit-fir.html
> +  <script type="text/javascript">
Didn't you add `nonce="{{ request.csp_nonce }}"` attributes for inline js before? Would prefer this block in a js file

2024-05-09 15:46 UTC, mikeylockwood commented on web/templates/web/domains/case/manage/edit-fir.html
> +      document.querySelector('input[name=send]').value = "False"
End js lines with `;`

2024-05-09 15:46 UTC, mikeylockwood approved these changes

2024-05-10 07:20 UTC, MattHolmes123 commented on web/templates/web/domains/case/manage/edit-fir.html
> +  </div>
Why does this display when the further information request is for an Access Reqest:
![image](https://github.com/uktrade/icms/assets/8921101/ebc88216-5dc1-4222-b4ff-d67a3e6c463c)
It shouldn't be shown

2024-05-10 07:23 UTC, MattHolmes123 commented on web/domains/case/views/utils.py
> +        application.status = model_class.Statuses.SUBMITTED
This code is called earlier Michael:

```
def application_in_processing(application: ImpOrExp) -> None:
    """Check if an application is being processed by a caseworker."""

    expected_status = [ST.SUBMITTED, ST.PROCESSING, ST.VARIATION_REQUESTED]
    expected_task = TT.PROCESS

    check_expected_status(application, expected_status)
    check_expected_task(application, expected_task)
```    

I'd be happy to leave this function as is as its just been extracted from the release_ownership view.

2024-05-10 07:25 UTC, MattHolmes123 commented on web/templates/partial/case/edit-fir.html
> +
Only have a single extra line

2024-05-10 07:30 UTC, MattHolmes123 requested changes
popup shouldn't display for access requests.

2024-05-15 11:17 UTC, MattHolmes123 commented on web/domains/case/fir/forms.py
> +)
We import as `from django import forms` more frequently than we do `from django.forms import foo, bar, baz`.
Would you mind doing it the first way (should reduce the overall line length).

2024-05-15 11:19 UTC, MattHolmes123 commented on web/domains/case/fir/forms.py
> +
All the django docs define js / css as lists of strings not tuples.
Not sure if it would ever cause issues but at least it would remove the need for the trailing `,`

2024-05-15 11:25 UTC, MattHolmes123 approved these changes

2024-05-15 11:51 UTC, chris-pettinga commented on web/domains/case/fir/forms.py
> +)
good spot will do, this is PyCharm doing me dirty

2024-05-15 12:34 UTC, merged