WIP - ICMSLST-2403 - Re-instate the Quick Issue button
uktrade/icms pull request #1520
Opened 2024-05-09 13:28 UTC by chris-pettinga

2024-05-09 19:56 UTC, MattHolmes123 commented on web/domains/case/utils.py
> +from ...utils.lock_manager import LockManager
No relative imports above the current directory.

2024-05-09 19:59 UTC, MattHolmes123 requested changes
Haven't reviewed this yet but can see this is only partly done.

I thought quick issue does the following:
1. The "start authorisation" step
2. The "Authorise documents" step.

So the outcome for an import application would be that it is with chief (or bypass chief when not enabled).
And the outcome for an export application would be that it is complete.

You'd have to check V1 though.

2024-05-10 07:35 UTC, MattHolmes123 commented
This banner is missing from the checklist view (not caused by you just noticed as part of this pr)
![image](https://github.com/uktrade/icms/assets/8921101/3e2fe863-d843-4fbe-8b99-e96647ebea12)
![image](https://github.com/uktrade/icms/assets/8921101/c3fd41d1-7e83-40ab-bd00-737047d188f4)

2024-05-10 07:36 UTC, MattHolmes123 commented on web/domains/case/utils.py
> +def start_application_authorisation(application: ImpOrExp, lock_manager: "LockManager") -> None:
No need for quotes.

2024-05-10 07:38 UTC, MattHolmes123 commented on web/domains/case/views/views_misc.py
> +    current_task_type = Task.TaskType.PROCESS
This doesn't reflect what is checked in the function based view for start authorisation:
`case_progress.application_in_processing(application)`
It won't work for variation requests.

2024-05-10 07:40 UTC, MattHolmes123 commented on web/domains/case/views/views_misc.py
> +    current_task_type = Task.TaskType.PROCESS
When clicking quick issue for an application with a variation request:
![image](https://github.com/uktrade/icms/assets/8921101/b1825211-790d-4e25-92be-7cb274b4dcda)

2024-05-10 07:53 UTC, MattHolmes123 commented on web/domains/case/views/views_misc.py
> +            return redirect(reverse("workbasket"))
I don't thin you want the whole method to be atomic, we are doing two separate units of work.
We should consider several blocks and let it get as far as it can. 
e.g. the authorise step works but fails on the document signing step.


Something like this
```
    def post(
        self, request: AuthenticatedHttpRequest, *args: Any, case_type: str, **kwargs: Any
    ) -> HttpResponse:
        self.set_application_and_task()

        #
        # Start authorisation step
        #
        with transaction.atomic():
            application_errors: ApplicationErrors = get_app_errors(self.application, case_type)
            if application_errors.has_errors():
                return redirect(
                    reverse(
                        "case:start-authorisation",
                        kwargs={"application_pk": self.application.pk, "case_type": case_type},
                    )
                )
            else:
                start_application_authorisation(self.application, request.icms.lock_manager)
        
        self.application.refresh_from_db()
        # Just did this so I didn't need to change the authorise documents code (as it's an example)
        application = self.application
        
        #
        # Authorise documents step
        #
        with transaction.atomic():
            # Use the authorise documents logic here (including the status/task checking)

            case_progress.application_is_authorised(application)
            task = case_progress.get_expected_task(application, Task.TaskType.AUTHORISE)

            if request.method == "POST":
                end_process_task(task, request.user)

                Task.objects.create(
                    process=application, task_type=Task.TaskType.DOCUMENT_SIGNING, previous=task
                )

                application.update_order_datetime()
                application.save()

                # Queues all documents to be created
                create_case_document_pack(application, request.user)

                messages.success(
                    request,
                    f"Authorise Success: Application {application.reference} has been queued for document signing",
                )

        return redirect(reverse("workbasket"))
```

2024-05-10 07:55 UTC, MattHolmes123 commented on web/domains/case/views/views_misc.py
> +            return redirect(reverse("workbasket"))
Also instead of doing this
```
        self.application.refresh_from_db()
        # Just did this so I didn't need to change the authorise documents code (as it's an example)
        application = self.application
```
You probably want to correctly fetch it from the db and select_for_update for the authorise documents step.

2024-05-15 13:30 UTC, MattHolmes123 commented on web/domains/case/utils.py
> +    from .tasks import create_case_document_pack
Why the need for this?

2024-05-15 13:32 UTC, MattHolmes123 commented on web/domains/case/views/views_misc.py
> +    @transaction.atomic()
Remove this

2024-05-15 13:43 UTC, MattHolmes123 commented on web/templates/web/domains/case/manage/base.html
> +      </form>
This PR throws an exception when you click quick when you refuse an application / variation request.

If you check V1 it will show that the Quick Issue feature only works when you are approving an application / variation request.


![image](https://github.com/uktrade/icms/assets/8921101/659dd415-24a3-41f1-a437-5fcbd66c5330)

2024-05-15 13:44 UTC, MattHolmes123 commented on web/tests/conftest.py
> +    return PngImageFile(image_file)
A duplicate of this fixture exists in `icms/web/tests/utils/pdf/test_signer.py`

2024-05-15 13:45 UTC, MattHolmes123 commented on web/tests/conftest.py
> +    return PngImageFile(image_file)
You can blame me for adding the fixture in `web/tests/domains/case/test_tasks.py` as I should have created a central fixture then.

2024-05-15 13:50 UTC, MattHolmes123 commented on web/domains/case/utils.py
> +    from .tasks import create_case_document_pack
I don't like to leave circular dependencies if I can help it.
Both functions you've added are only used in `views_misc.py`.

If you move them both back there the circular dependency issue should resolve itself.

2024-05-15 13:53 UTC, MattHolmes123 requested changes
A quick test shows this throws an exception when you either refuse an application or variation request.
Checking V1 also shows that the feature should only be enabled when an application or variation request are going to be approved.

2024-05-17 10:22 UTC, chris-pettinga commented on web/domains/case/views/views_misc.py
> +    @transaction.atomic()
@MattHolmes123 - how else are we going to protect the view?

2024-05-17 10:48 UTC, MattHolmes123 commented on web/domains/case/views/views_misc.py
> +    @transaction.atomic()
We have two atomic blocks in the view (one per step)
![image](https://github.com/uktrade/icms/assets/8921101/aea0e882-8779-4ca5-9c85-a90d5836d023)

We don't need the outer one.

2024-05-17 10:49 UTC, MattHolmes123 commented on web/domains/case/views/views_misc.py
> +    @transaction.atomic()
They should be treated as two seperate units of work and I'd rather it commit after the first block.

2024-05-17 12:04 UTC, chris-pettinga commented on web/domains/case/views/views_misc.py
> +    @transaction.atomic()
@MattHolmes123 sorry apologies I thought you were talking about the 
```
current_task_type = Task.TaskType.PROCESS
permission_required = [Perms.sys.ilb_admin]
```

block, have removed transaction.etomic

2024-05-20 10:15 UTC, MattHolmes123 requested changes
Still fails when you try to quick issue a refused variation request.
![image](https://github.com/uktrade/icms/assets/8921101/1a0deba6-755f-4b12-864b-7ef463717a27)

2024-05-20 13:46 UTC, chris-pettinga commented
@MattHolmes123 - have added some conditionals to check if it's a variation request, ready for re-review

2024-05-20 14:12 UTC, chris-pettinga commented
@MattHolmes123 ignore me, need to also take into account Export applications.

2024-05-21 07:02 UTC, MattHolmes123 commented on web/templates/web/domains/case/manage/base.html
> +          <input type="button" class="button" value="Quick Issue" data-modal-message="The case must be approved to issue a licence."/>
```html
        {% if (process.status == "PROCESSING" and process.decision == "APPROVE") or (process.status == "VARIATION_REQUESTED" and process.variation_decision == "APPROVE") %}
          <input type="submit" class="button" value="Quick Issue"/>
        {% else %}
          <input type="button" class="button" value="Quick Issue" data-modal-message="The case must be approved to issue a licence."/>
        {% endif %}
```

2024-05-21 07:05 UTC, MattHolmes123 commented on web/domains/case/_import/models.py
> +    def can_quick_issue(self) -> bool:
We don't need these model methods, the logic is the same for import and export applications.

2024-05-21 07:05 UTC, MattHolmes123 commented on web/templates/web/domains/case/manage/base.html
> +        {% endif %}
```
        {% if (process.status == "PROCESSING" and process.decision == "APPROVE") or (process.status == "VARIATION_REQUESTED" and process.variation_decision == "APPROVE") %}
          <input type="submit" class="button" value="Quick Issue"/>
        {% else %}
          <input type="button" class="button" value="Quick Issue" data-modal-message="The case must be approved to issue a licence."/>
        {% endif %}
```

2024-05-21 07:07 UTC, MattHolmes123 commented on web/domains/case/views/views_misc.py
> +        ImpExpStatus.SUBMITTED,
Remove SUBMITTED as it's not required for this view.
The only reason SUBMITTED is checked in other caseworker views is because caseworkers can review readonly cases that have not been picked up by a caseworker yet.

2024-05-21 07:49 UTC, MattHolmes123 requested changes
Added a few comments but mostly just fixed them here for you to review and test:
https://github.com/uktrade/icms/pull/1545

2024-05-21 07:49 UTC, MattHolmes123 commented on web/templates/web/domains/case/manage/base.html
> +{% endblock %}
missing newline

2024-05-21 07:49 UTC, MattHolmes123 commented on web/domains/case/views/views_misc.py
> +        ImpExpStatus.SUBMITTED,
Fixed in my pr:
https://github.com/uktrade/icms/pull/1545

2024-05-23 08:50 UTC, MattHolmes123 commented on web/domains/case/views/views_misc.py
> +                    and self.application.variation_decision == self.application.REFUSE
This should be `and self.application.variation_decision == self.application.APPROVE`

Can you add a test for doing a quick issue on an app with a variation request, it's an important path to test.

2024-05-23 16:00 UTC, marcuspp approved these changes

2024-05-24 07:38 UTC, MattHolmes123 approved these changes

2024-05-24 08:37 UTC, merged