ICMSLST-2858 - Sanctions licence PDF -> Styling bugs
uktrade/icms pull request #1682
Opened 2024-07-26 14:06 UTC by chris-pettinga

2024-07-26 14:35 UTC, mikeylockwood commented on web/templates/pdf/import/sanctions-licence.html
> +            <p class="row min-height-40">Email: <a href="mailto:importcontrols@businessandtrade.gov.uk">importcontrols@businessandtrade.gov.uk</a></p>{# /PS-IGNORE #}
I don't think this should be hardcoded in. We can just change the value in the test environment if they really want to see it in the test pdfs

2024-07-26 15:44 UTC, chris-pettinga commented on web/templates/pdf/import/sanctions-licence.html
> +            <p class="row min-height-40">Email: <a href="mailto:importcontrols@businessandtrade.gov.uk">importcontrols@businessandtrade.gov.uk</a></p>{# /PS-IGNORE #}
@mikeylockwood unless I'm mistaken this is the only place that this specific email address is used? If so then it feels a bit unnecessary to do the whole env var rigamarole

2024-07-26 15:48 UTC, MattHolmes123 commented on web/templates/pdf/import/sanctions-licence.html
> +            <p class="row min-height-40">Email: <a href="mailto:importcontrols@businessandtrade.gov.uk">importcontrols@businessandtrade.gov.uk</a></p>{# /PS-IGNORE #}
elsewhere we do this: `<a href="mailto:{{ ilb_contact_email }}">{{ ilb_contact_email }}</a>`
Might as well be a context variable reading from a setting in my book

2024-07-29 08:15 UTC, chris-pettinga commented on web/templates/pdf/import/sanctions-licence.html
> +            <p class="row min-height-40">Email: <a href="mailto:importcontrols@businessandtrade.gov.uk">importcontrols@businessandtrade.gov.uk</a></p>{# /PS-IGNORE #}
@MattHolmes123 @mikeylockwood this email address is different from the typical value set by `ilb_contact_email` so it would mean the inclusion of another env var

2024-07-29 08:15 UTC, marcuspp commented on web/templates/pdf/import/sanctions-licence.html
> +            <p class="row min-height-40">Email: <a href="mailto:importcontrols@businessandtrade.gov.uk">importcontrols@businessandtrade.gov.uk</a></p>{# /PS-IGNORE #}
This has a separate ticket which i am doing today and will create a settings for it.

2024-07-29 13:39 UTC, marcuspp requested changes
The holders box is no longer in line at the bottom with the start of section 10.

2024-07-29 13:39 UTC, marcuspp commented on pii-ner-exclude.txt
> +importcontrols@businessandtrade.gov.uk">importcontrols@businessandtrade.gov.uk</a></p
Remove as this no longer part of the PR

2024-07-29 13:39 UTC, marcuspp commented on web/templates/pdf/import/sanctions-licence.html
> +               <p style="align-self: flex-end;margin-right:35px;">{{ licence_start_date }}</p>
Change to class functions as these are the only two inline styles and this file has its only dedicated css so we should use it

2024-07-29 13:39 UTC, marcuspp commented on web/utils/pdf/pages.py
> +            new_page.line(left_margin - 25, 791, left_margin - 25, 467)
I think this would read better if it was 
```
top_margin = 794
if page_number == 0:
    top_margin = 791
```    
Less if statements

2024-07-29 15:22 UTC, chris-pettinga commented on web/utils/pdf/pages.py
> +            new_page.line(left_margin - 25, 791, left_margin - 25, 467)
@marcuspp good idea thank you

2024-07-30 11:49 UTC, marcuspp approved these changes

2024-07-30 12:07 UTC, merged