ICMSLST-2930 Template.Codes refactor.
uktrade/icms pull request #1747
Opened 2024-08-28 10:16 UTC by MattHolmes123

2024-08-28 20:45 UTC, marcuspp requested changes
I think anywhere where you are creating a case email the email type should be a `CaseEmailCode`

2024-08-28 20:45 UTC, marcuspp commented on web/mail/emails.py
> +    template_code = email_type
The CaseEmail model has choices as `CASE_EMAIL_TYPES` for this field

2024-08-29 07:01 UTC, MattHolmes123 commented on web/mail/emails.py
> +    email_type: TemplateCodes,
Yer I agree (I nearly changed it to this before I submitted the PR).
I added TemplateCodes quite late in the PR and I'd already typed create_case_email.

2024-08-29 07:02 UTC, MattHolmes123 commented on web/mail/emails.py
> +    email_type: TemplateCodes,
Actually no I've remembered why I left it as is.

2024-08-29 07:07 UTC, MattHolmes123 commented on web/mail/emails.py
> +    email_type: TemplateCodes,
I've rememered why I left it as I did.
<img width="1311" alt="image" src="https://github.com/user-attachments/assets/0335fc35-e274-4ab2-bc39-13bf768a41aa">
create_case_email calls `get_email_template_subject_body` to fetch the template and that is correctly typed like this:

![image](https://github.com/user-attachments/assets/4fd9f1f5-15f1-4e55-9fec-1cea14b3368e)

2024-08-29 12:05 UTC, marcuspp approved these changes

2024-08-29 14:23 UTC, merged