ICMSLST-2519 - Removed the use of pyOpenSSL
uktrade/icms pull request #1767
Opened 2024-09-10 14:18 UTC by marcuspp

2024-09-10 14:21 UTC, marcuspp commented on web/tests/utils/pdf/test_signer.py
> +    key_and_certificate = pkcs12.load_key_and_certificates(
Added this test to make sure the certificate is always the dummy one.

2024-09-10 14:23 UTC, marcuspp commented on requirements-base.txt
> -paramiko~=3.4       # endesive sub-dependency
Not sure if these should still be pinned or not in `requirements-base.in` .

2024-09-10 14:25 UTC, marcuspp commented on requirements-base.in
> +cryptography==43.0.1
Updated

2024-09-10 14:25 UTC, marcuspp commented on requirements-base.in
> +endesive==2.17.2
Updated

2024-09-10 14:25 UTC, marcuspp commented on requirements-base.in
> +pypdf==4.3.1
Updated

2024-09-10 14:26 UTC, marcuspp commented on requirements-base.in
> +requests==2.32.3
Updated

2024-09-10 14:28 UTC, marcuspp commented on requirements-dev.in
> +pip-tools==7.4.1
Added

2024-09-10 14:32 UTC, mikeylockwood approved these changes

2024-09-10 14:33 UTC, MattHolmes123 commented on requirements-base.txt
> -paramiko~=3.4       # endesive sub-dependency
They were pinned because endesive does not pin its dependencies at all and presumably we had an issue with this one:
`pykcs11==1.4.4      # endesive sub-dependency (>=1.5 macOS install bug)`

2024-09-10 14:35 UTC, MattHolmes123 commented on requirements-base.txt
> -paramiko~=3.4       # endesive sub-dependency
This has now been updated
pykcs11==1.5.16
    # via endesive

2024-09-10 14:49 UTC, MattHolmes123 commented on requirements-base.txt
> -paramiko~=3.4       # endesive sub-dependency
Maybe it's not an issue anymore but I do think that the endesive sub depenedencies will just update to their latest versions whenever we check for updates in the requirements files (even if we pin endesive)

2024-09-16 11:09 UTC, marcuspp commented on requirements-base.txt
> -paramiko~=3.4       # endesive sub-dependency
Added back

2024-09-16 13:35 UTC, MattHolmes123 commented on documentation/managing-dependencies.md
> +pip install -r requirements-dev.txt
We have `make setup` as part of the setup process.
Part of that command runs this: `scripts/initial-setup.sh`
Therefore there should be no manual step required here and instead it should be done automatically in `scripts/initial-setup.sh`

2024-09-16 13:39 UTC, MattHolmes123 commented on documentation/managing-dependencies.md
> +pip install -r requirements-dev.txt
As `pip install -r requirements-dev.txt` is already done in `scripts/initial-setup.sh` I would just say "run `make setup` (if anything)

2024-09-16 13:40 UTC, MattHolmes123 commented on documentation/managing-dependencies.md
> +pip install -r requirements-dev.txt
I say this becuase make setup installs everything in to a venv, the example here doesn't do that.

2024-09-16 13:41 UTC, MattHolmes123 requested changes
s

2024-09-16 14:41 UTC, merged