ICMSLST-2869 - FA-SIL UI Improvements
uktrade/icms pull request #1853
Opened 2024-10-11 11:16 UTC by marcuspp

2024-10-11 11:35 UTC, marcuspp commented on web/templates/partial/know-bought-from.html
> +{% elif process.know_bought_from == True and not contacts %}
Not related but whilst testing I don't think this should be shown if a contact has already been added

2024-10-11 11:41 UTC, MattHolmes123 commented on web/templates/web/domains/case/import/fa-sil/view.html
> -      <a href="#view-licence-for">Goods - Licence For</a>
Why? Whats the harm in having links that take you to each section?

2024-10-11 11:43 UTC, MattHolmes123 commented on web/templates/web/domains/case/import/fa-sil/view.html
> -      <a href="#view-licence-for">Goods - Licence For</a>
Oh I see, it's right next to the tiny goods section
```jinja
{% call application_section("Goods", "view-goods") %}
    {{ application_field(process.commodity_code, "Commodity Code") }}

    <hr />
```

2024-10-11 11:47 UTC, marcuspp commented on web/templates/web/domains/case/import/fa-sil/view.html
> -      <a href="#view-licence-for">Goods - Licence For</a>
The screen was cluttered and the link offered no value as everything is very close together

2024-10-11 11:53 UTC, MattHolmes123 commented on web/templates/web/domains/case/import/fa-sil/view.html
>    {% endcall %}
Not sure about this change. I will test it after lunch.

2024-10-11 11:53 UTC, MattHolmes123 requested changes
I need to test something

2024-10-16 13:36 UTC, MattHolmes123 commented
Added a better screenshot @marcuspp including all 4 types of certificates.

Before:
![image](https://github.com/user-attachments/assets/c54782f4-9909-4bf3-b3d0-b213a572f07c)

After:
![image](https://github.com/user-attachments/assets/38d5bc40-bf5a-44d5-93a8-a6ce983d1305)

2024-10-16 13:37 UTC, MattHolmes123 approved these changes

2024-10-16 14:29 UTC, merged