ICMSLST-444 Add/remove contacts for exporter
uktrade/icms pull request #196
Opened 2020-10-06 16:29 UTC by kevinetienne

2020-10-07 12:43 UTC, kevinetienne commented on web/domains/exporter/forms.py
> +        queryset=User.objects.all(), widget=ContactWidget, required=False
Filter by account status

2020-10-07 12:43 UTC, kevinetienne commented on web/domains/exporter/forms.py
> +        queryset=User.objects.all(), widget=ContactWidget, required=False
Plus exclude people already assigned as contacts

2020-10-07 12:43 UTC, kevinetienne commented on web/domains/exporter/forms.py
> +        return f"{user.full_name} - {user.email}"
move to `widgets.py`

2020-10-07 12:43 UTC, kevinetienne commented on web/domains/exporter/urls.py
> +    path("create/", views.create, name="exporter-create"),
2 new endpoints:
 - add contact for exporter
 - delete contact for exporter

2020-10-07 12:43 UTC, kevinetienne commented on web/domains/exporter/views.py
> +permissions = "web.exporter_access"
use inline

2020-10-07 12:43 UTC, kevinetienne commented on web/domains/exporter/views.py
> +def edit(request, pk):
`edit_exporter`

2020-10-07 12:43 UTC, kevinetienne commented on web/domains/exporter/views.py
> +def create(request):
`create_exporter`

2020-10-07 12:43 UTC, kevinetienne commented on web/domains/exporter/views.py
> +            return redirect(reverse("exporter-list"))
go to edit

2020-10-07 12:43 UTC, kevinetienne commented on web/domains/exporter/views.py
>      permission_required = permissions
remove

2020-10-07 12:43 UTC, kevinetienne commented on web/templates/partial/exporter/sidebar.html
> +        <a href="{{ url('exporter-list') }}">Access Requests</a>
It's not Access Requests

2020-10-07 12:43 UTC, kevinetienne commented on web/templates/web/contacts/grid.html
>          There isn't anyone in this team
There is no contact attached to this exporter

2020-10-07 12:43 UTC, kevinetienne commented on web/templates/web/contacts/grid.html
> +                <th>Delete contact</th>
Actions

2020-10-07 12:43 UTC, kevinetienne commented on web/tests/domains/exporter/test_views.py
> +PERMISSIONS = ["exporter_access"]
inline

2020-10-09 10:12 UTC, oskusalerma requested changes

2020-10-09 10:12 UTC, oskusalerma commented on web/domains/exporter/views.py
> +        .exclude(pk__in=exporter_contacts)
can i see the sql for this just to verify it's doing what we think it's doing

2020-10-09 10:12 UTC, oskusalerma commented on web/domains/exporter/views.py
> +    form = ExporterForm()
same thing here, put in else

2020-10-09 10:12 UTC, oskusalerma commented on web/domains/user/managers.py
> +        return self.filter(account_status="ACTIVE")
try doing self.model.ACTIVE?

2020-10-09 10:12 UTC, oskusalerma commented on web/templates/partial/contacts/contacts.html
> +        There are no contacts attached to this exporter
reword this so we can share with importer

2020-10-09 10:12 UTC, oskusalerma commented on web/templates/partial/contacts/contacts.html
> +                                action="{{ url('exporter-contact-delete', kwargs={'pk': object.pk, 'contact_pk': user.pk}) }}">
on the import ticket you might have to move this out to a block so importer can have its own urls

2020-10-09 10:28 UTC, kevinetienne commented on web/domains/exporter/views.py
> +        .exclude(pk__in=exporter_contacts)
This is the query

```python
from guardian.shortcuts import get_users_with_perms
from web.models import User


>> qs = get_users_with_perms(Exporter.objects.get(pk=16), only_with_perms_in=["is_contact_of_exporter"]).filter(user_permissions__codename="exporter_access")

>> User.objects.account_active().filter(user_permissions__codename="exporter_access").exclude(pk__in=qs)
<QuerySet []>

>> str(User.objects.account_active().filter(user_permissions__codename="exporter_access").exclude(pk__in=qs).query)
```

```sql
'SELECT * 
  FROM "web_user"
  INNER JOIN "web_user_user_permissions" ON ("web_user"."id" = "web_user_user_permissions"."user_id")
  INNER JOIN "auth_permission" ON ("web_user_user_permissions"."permission_id" = "auth_permission"."id") 
  WHERE ("web_user"."account_status" = ACTIVE AND "auth_permission"."codename" = exporter_access AND NOT ("web_user"."id" IN (SELECT DISTINCT V0."id" FROM "web_user" V0 LEFT OUTER JOIN "guardian_userobjectpermission" V1 ON (V0."id" = V1."user_id") LEFT OUTER JOIN "web_user_groups" V4 ON (V0."id" = V4."user_id") INNER JOIN "web_user_user_permissions" V6 ON (V0."id" = V6."user_id") INNER JOIN "auth_permission" V7 ON (V6."permission_id" = V7."id") WHERE ((V1."content_type_id" = 33 AND V1."object_pk" = 16 AND V1."permission_id" IN (SELECT U0."id" FROM "auth_permission" U0 WHERE (U0."codename" IN (is_contact_of_exporter) AND U0."content_type_id" = 33))) AND V7."codename" = exporter_access)))) ORDER BY "web_user"."is_active" DESC, "web_user"."first_name" ASC'
```

Not that:
```python
>> qs = get_users_with_perms(Exporter.objects.get(pk=16), only_with_perms_in=["is_contact_of_exporter"]).filter(user_permissions__codename="exporter_access")
```
generates 

```sql
'SELECT * FROM "web_user" INNER JOIN "web_user_user_permissions" ON ("web_user"."id" = "web_user_user_permissions"."user_id") INNER JOIN "auth_permission" ON ("web_user_user_permissions"."permission_id" = "auth_permission"."id") WHERE ("web_user"."account_status" = ACTIVE AND "auth_permission"."codename" = exporter_access AND NOT ("web_user"."id" IN (SELECT DISTINCT V0."id" FROM "web_user" V0 LEFT OUTER JOIN "guardian_userobjectpermission" V1 ON (V0."id" = V1."user_id") LEFT OUTER JOIN "web_user_groups" V4 ON (V0."id" = V4."user_id") INNER JOIN "web_user_user_permissions" V6 ON (V0."id" = V6."user_id") INNER JOIN "auth_permission" V7 ON (V6."permission_id" = V7."id") WHERE ((V1."content_type_id" = 33 AND V1."object_pk" = 16 AND V1."permission_id" IN (SELECT U0."id" FROM "auth_permission" U0 WHERE (U0."codename" IN (is_contact_of_exporter) AND U0."content_type_id" = 33))) AND V7."codename" = exporter_access)))) ORDER BY "web_user"."is_active" DESC, "web_user"."first_name" ASC'
```

which is what you see partially after the `NOT` in the where clause.

2020-10-09 10:37 UTC, kevinetienne commented on web/templates/partial/contacts/contacts.html
> +        There are no contacts attached to this exporter
Fixed in https://github.com/uktrade/icms/pull/196/commits/6226c0bd9fc2d3bf6e5ce36749827bb0bd6dc041

2020-10-09 10:37 UTC, kevinetienne commented on web/domains/user/managers.py
> +        return self.filter(account_status="ACTIVE")
Fixed in https://github.com/uktrade/icms/pull/196/commits/6226c0bd9fc2d3bf6e5ce36749827bb0bd6dc041

2020-10-09 10:38 UTC, kevinetienne commented on web/domains/exporter/views.py
> +    form = ExporterForm()
Updated in https://github.com/uktrade/icms/pull/196/commits/6226c0bd9fc2d3bf6e5ce36749827bb0bd6dc041

2020-10-09 12:20 UTC, oskusalerma approved these changes

2020-10-09 12:22 UTC, merged