ICMSLST-492 Allow Importer to create/view/retract withdrawal
uktrade/icms pull request #261
Opened 2021-02-03 15:56 UTC by kevinetienne

Withdraw application for Firearms and Ammunition (OIL)

2021-02-03 16:03 UTC, oskusalerma requested changes

2021-02-03 16:03 UTC, oskusalerma commented on web/domains/case/_import/views.py
> +        except Exception:
This is too generic, can you make get_task raise specific exceptions for the different errors it can encounter and then catch the one(s) you want here? you can add the new exception classes in `web/flow/errors.py` or something

2021-02-03 16:03 UTC, oskusalerma commented on web/domains/case/_import/views.py
> +        except Exception:
same here

2021-02-04 10:21 UTC, trbateman approved these changes

2021-02-04 10:24 UTC, trbateman requested changes
Change

2021-02-04 14:41 UTC, kevinetienne commented on web/domains/case/_import/views.py
> +        except Exception:
Updated in https://github.com/uktrade/icms/pull/261/commits/97d79ef62e93a09fc832f8251c4587b0143bda9d, we decided to allow get_task to accept one or many expected states.

2021-02-04 14:41 UTC, kevinetienne commented on web/domains/case/_import/views.py
> +        except Exception:
Updated in https://github.com/uktrade/icms/pull/261/commits/97d79ef62e93a09fc832f8251c4587b0143bda9d, we decided to allow get_task to accept one or many expected states.

2021-02-04 14:44 UTC, oskusalerma approved these changes

2021-02-04 15:06 UTC, merged