ICMSLST-536 Add country groups data migration.
uktrade/icms pull request #275
Opened 2021-02-19 14:07 UTC by trbateman

2021-02-19 14:22 UTC, oskusalerma requested changes

2021-02-19 14:22 UTC, oskusalerma commented on web/domains/country/models.py
> +        unique_together = ["name", "is_active"]
unique_together is deprecated: https://docs.djangoproject.com/en/3.1/ref/models/options/#unique-together

use UniqueConstraint instead. see web/domains/template/models.py for an example

2021-02-19 14:22 UTC, oskusalerma commented on web/domains/country/models.py
> -        if self.id:
why are you changing this?

2021-02-19 14:22 UTC, oskusalerma commented on web/domains/country/models.py
> +    comments = models.TextField(blank=True, null=True)
why are you changing this from charfield to textfield, and in effect, removing the max length?

2021-02-19 14:22 UTC, oskusalerma commented on web/domains/country/models.py
> -        if self.id:
why are you changing this?

2021-02-19 14:22 UTC, oskusalerma commented on web/migrations/0027_add_country_data.py
>                  hmrc_code="CG",
umm, migration 26 has been merged to develop, me and kevin have run it, you can't just change history now.

2021-02-19 14:47 UTC, trbateman commented on web/domains/country/models.py
> -        if self.id:
Returning name gives a more meaningful description of the object, especially in the admin.

2021-02-19 14:47 UTC, trbateman commented on web/domains/country/models.py
> +        unique_together = ["name", "is_active"]
Thanks for heads up. It's not deprecated at the moment but might be in the future, hence no deprecation warnings coming up.

2021-02-19 14:47 UTC, trbateman commented on web/domains/country/models.py
> +    comments = models.TextField(blank=True, null=True)
Text field feels more appropriate given the string has line breaks in it. The default widget is therefore more suitable for django admin.

2021-02-19 14:47 UTC, trbateman commented on web/domains/country/models.py
> -        if self.id:
Same as above

2021-02-19 14:47 UTC, trbateman commented on web/migrations/0027_add_country_data.py
>                  hmrc_code="CG",
Will give you a call about this.

2021-02-22 11:49 UTC, oskusalerma approved these changes

2021-02-22 13:29 UTC, merged