ICMSLST-511 Generate pdf preview for licence and cover letter
uktrade/icms pull request #301
Opened 2021-03-17 15:07 UTC by kevinetienne

2021-03-17 15:19 UTC, oskusalerma requested changes

2021-03-17 15:19 UTC, oskusalerma commented on web/domains/case/_import/views.py
> +from weasyprint import HTML
don't do that, extremely confusing name later in the file. just import weasyprint and then do `weasyprint.HTML(...)` later

2021-03-17 15:19 UTC, oskusalerma commented on web/domains/case/_import/views.py
> +        pdf_file = html.write_pdf()
in an earlier job we hit problems with weasyprint on server machines that didn't have X server running
which they obviously won't
everything was fine on developer machines, but production didn't work
so i would like you to add a test using weasyprint to create a PDF
so we know whether it works without an X server

2021-03-17 15:19 UTC, oskusalerma commented on web/domains/case/_import/views.py
> +        response["Content-Disposition"] = "filename=Cover Letter.pdf"
do we really want a space in the filename?

2021-03-17 15:19 UTC, oskusalerma commented on web/domains/case/_import/models.py
> +        return self.issue_date or timezone.now()
issue_date is Date, timezone.now() is Datetime, so this seems wrong

2021-03-17 16:24 UTC, kevinetienne commented on web/domains/case/_import/models.py
> +        return self.issue_date or timezone.now()
Fixed in https://github.com/uktrade/icms/pull/301/commits/e4055daa0ab8f6c1b0dd2b9b741e4cb609aac359, calling now `timezone.now().date()`.

2021-03-17 16:24 UTC, kevinetienne commented on web/domains/case/_import/views.py
> +        response["Content-Disposition"] = "filename=Cover Letter.pdf"
You're probably right I've copied the filename from the initial system. I've removed it in https://github.com/uktrade/icms/pull/301/commits/e4055daa0ab8f6c1b0dd2b9b741e4cb609aac359

2021-03-17 16:25 UTC, kevinetienne commented on web/domains/case/_import/views.py
> +        pdf_file = html.write_pdf()
Added two tests in https://github.com/uktrade/icms/pull/301/commits/e4055daa0ab8f6c1b0dd2b9b741e4cb609aac359. It looks like early versions of weasyprint were relying on `GTK/GDK` which in turn used to require some x libraries.

2021-03-17 16:26 UTC, kevinetienne commented on web/domains/case/_import/views.py
> +from weasyprint import HTML
You're totally right fixed in https://github.com/uktrade/icms/pull/301/commits/e4055daa0ab8f6c1b0dd2b9b741e4cb609aac359

2021-03-18 09:09 UTC, oskusalerma requested changes

2021-03-18 09:09 UTC, oskusalerma commented on web/tests/domains/case/_import/test_views.py
> +    assert response["Content-Disposition"] == "filename=CoverLetter.pdf"
can you check the actual data a little bit, so there's some confidence the PDF generation has worked? PDF files start with `%PDF-` (see https://en.wikipedia.org/wiki/List_of_file_signatures), and I guess you could also check the file size is within 10% of what you're expecting?

2021-03-18 09:09 UTC, oskusalerma commented on web/tests/domains/case/_import/test_views.py
> +    assert response["Content-Disposition"] == "filename=Licence.pdf"
same here

2021-03-18 10:23 UTC, kevinetienne commented on web/tests/domains/case/_import/test_views.py
> +    assert response["Content-Disposition"] == "filename=CoverLetter.pdf"
Updated in https://github.com/uktrade/icms/pull/301/commits/db42dbf0c52935f595c45c6040a4e47d92cf5418

2021-03-18 10:49 UTC, kevinetienne commented on web/tests/domains/case/_import/test_views.py
> +    assert response["Content-Disposition"] == "filename=Licence.pdf"
Updated in https://github.com/uktrade/icms/pull/301/commits/815e639c822d1e96d7eb60cc7b1769ebdb09192c

2021-03-18 10:51 UTC, oskusalerma approved these changes

2021-03-18 11:19 UTC, merged