ICMSLST-621 Add commodity data
uktrade/icms pull request #340
Opened 2021-04-23 12:11 UTC by kevinetienne

* use CharField for commodity code in firearms and sanctions
 * remove CommodityType.allowed_code

2021-04-23 12:31 UTC, MattHolmes123 requested changes

2021-04-23 12:31 UTC, MattHolmes123 commented on web/migrations/0052_add_commodity_data.py
> +    Unit.objects.get_or_create(
I think this will slow down the tests quite a bit.

We should maybe use this rather than get_or_create as we know its new data:
https://docs.djangoproject.com/en/3.2/ref/models/querysets/#bulk-create
It includes an example of inserting data in batches.

We could also record the time it takes to run these migrations both ways to see how much better it is

2021-04-23 12:42 UTC, oskusalerma commented on web/migrations/0052_add_commodity_data.py
> +    Unit.objects.get_or_create(
I agree with Matt's comment, thousands of get_or_create calls will be quite slow, bulk_create would be much better.

2021-04-23 12:43 UTC, oskusalerma requested changes
see above

2021-04-26 10:38 UTC, oskusalerma approved these changes

2021-04-26 10:47 UTC, MattHolmes123 approved these changes

2021-04-26 10:56 UTC, merged