ICMSLST-620 Update firearms user cerificates to match wood certificates.
uktrade/icms pull request #342
Opened 2021-04-26 10:55 UTC by MattHolmes123

Changes:
  - Can download certifcate file
  - Each certificate can only have one file
  - Updated UI to match wood certificates
  - Added delete certificate view
  - Updated constabulary email templates to work with changed model.

2021-04-26 13:40 UTC, kevinetienne commented on web/domains/case/_import/firearms/urls.py
> +        "oil/<int:application_pk>/certificates/<int:certificate_pk>/delete",
Can you add a trailing slash at the end please?

2021-04-26 15:01 UTC, oskusalerma requested changes

2021-04-27 07:35 UTC, MattHolmes123 commented on web/domains/case/_import/firearms/views.py
> +                        kwargs={"pk": application_pk},
It adds it back in

2021-04-27 07:56 UTC, oskusalerma approved these changes

2021-04-27 07:57 UTC, merged