Refactor ImportApplicationTypes types and subtypes to use TextChoices.
uktrade/icms pull request #365
Opened 2021-05-06 13:43 UTC by MattHolmes123

2021-05-06 14:13 UTC, oskusalerma requested changes

2021-05-06 14:13 UTC, oskusalerma commented on web/domains/case/_import/models.py
> +    class AppTypes(models.TextChoices):
as discussed offline:

- enum names should be uppercase
- apptypes -> Types
- AppSubTypes -> SubTypes
- shorten names (e.g. firearms_ammunition_code -> firearms, etc)

2021-05-06 14:13 UTC, oskusalerma commented on web/domains/case/_import/models.py
> +        degrogation_from_sanctions_ban = ("SAN", "Derogation from Sanctions Import Ban")
fix the typo while you're at it (degrogation -> derogation)

2021-05-06 14:31 UTC, oskusalerma approved these changes

2021-05-07 08:45 UTC, oskusalerma requested changes

2021-05-07 08:45 UTC, oskusalerma commented on web/domains/case/_import/fa_dfl/models.py
> +    """Firearms & Ammunition Deactivated Firearms Licence application class"""
you don't have to say class

2021-05-07 08:45 UTC, oskusalerma commented on web/domains/case/_import/views.py
> +    """Create a Firearms & Ammunition - Deactivated Firearms Licence application."""
not sure this comment is adding any value

2021-05-07 08:45 UTC, oskusalerma commented on web/migrations/0060_add_dflapplication.py
> +# Generated by Django 3.1.8 on 2021-05-07 07:37
60 is already used

2021-05-07 08:46 UTC, MattHolmes123 commented on web/migrations/0060_add_dflapplication.py
> +# Generated by Django 3.1.8 on 2021-05-07 07:37
Ahh yer just rebased and got 60

2021-05-07 08:59 UTC, kevinetienne approved these changes

2021-05-07 09:09 UTC, oskusalerma approved these changes

2021-05-07 09:20 UTC, merged