Add/edit/view Goods sections
uktrade/icms pull request #383
Opened 2021-05-14 15:05 UTC by kevinetienne

Add forms and views for the following goods:
 - section 1;
 - section 2;
 - section 5;
 - section 58(2) - obsolete;
 - section 58(2) - other.

2021-05-17 14:32 UTC, oskusalerma requested changes

2021-05-17 14:32 UTC, oskusalerma commented on web/domains/case/_import/fa_sil/urls.py
> +    path("<int:pk>/sections/choice/", views.choose_goods_section, name="choose-goods-section"),
s/choice/choose/

2021-05-17 14:32 UTC, oskusalerma commented on web/domains/case/_import/fa_sil/views.py
> +        application = get_object_or_404(models.SILApplication.objects.select_for_update(), pk=pk)
can type this variable, same in all other funcs

2021-05-18 09:29 UTC, kevinetienne commented on web/domains/case/_import/fa_sil/views.py
> +        application = get_object_or_404(models.SILApplication.objects.select_for_update(), pk=pk)
fixed in https://github.com/uktrade/icms/pull/383/commits/7ca781037bff7310a53bf45e85e6d89d6a57cb9a

2021-05-18 09:56 UTC, oskusalerma requested changes

2021-05-18 09:56 UTC, oskusalerma commented on web/domains/case/_import/fa_sil/urls.py
> +                path("add/", views.add_goods, name="add-section"),
why the mismatch between function/view names? they should both be goods or section, confusing now when they're different. goes for all of these.

2021-05-18 09:56 UTC, oskusalerma commented on web/domains/case/_import/fa_sil/views.py
> +class CreateSILSectionConfig(NamedTuple):
please have all type definitions at top of files, not hidden between functions

2021-05-18 09:56 UTC, oskusalerma commented on web/domains/case/_import/fa_sil/views.py
> +    raise NotImplementedError("sil_section_type is not supported: {sil_section_type}")
you forgot f prefix

2021-05-18 10:17 UTC, kevinetienne commented on web/domains/case/_import/fa_sil/views.py
> +    raise NotImplementedError("sil_section_type is not supported: {sil_section_type}")
updated in https://github.com/uktrade/icms/pull/383/commits/2dca9e9eb3efc4243607770a1f18558fbcfdbf08

2021-05-18 10:17 UTC, kevinetienne commented on web/domains/case/_import/fa_sil/views.py
> +class CreateSILSectionConfig(NamedTuple):
Updated in https://github.com/uktrade/icms/pull/383/commits/2dca9e9eb3efc4243607770a1f18558fbcfdbf08

2021-05-18 10:18 UTC, kevinetienne commented on web/domains/case/_import/fa_sil/urls.py
> +                path("add/", views.add_goods, name="add-section"),
Yeah it shows I was hesitating between goods and sections, fixed in https://github.com/uktrade/icms/pull/383/commits/2dca9e9eb3efc4243607770a1f18558fbcfdbf08

2021-05-18 10:35 UTC, oskusalerma approved these changes

2021-05-18 11:02 UTC, merged