ICMSLST-681 Refactor authorise views and fix checklist validation bug.
uktrade/icms pull request #399
Opened 2021-05-25 12:28 UTC by MattHolmes123

2021-05-25 13:08 UTC, kevinetienne approved these changes

2021-05-25 13:12 UTC, oskusalerma requested changes

2021-05-25 13:12 UTC, oskusalerma commented on web/domains/case/_import/urls.py
> -                #
can you change the comment on line 58-59 to say "these are..."

2021-05-25 13:12 UTC, oskusalerma commented on web/domains/case/urls.py
> +                # Application Authorisation (import/export
missing end paren

2021-05-25 13:12 UTC, oskusalerma commented on web/domains/case/urls.py
> +    path("start-authorisation/", views.start_authorisation, name="start-authorisation"),
these are all prefixed with authorisation, can be just start / cancel (the URLs)

2021-05-25 13:12 UTC, oskusalerma commented on web/domains/case/views.py
> +        #     ...
TODO comment here, maybe even raise NotImplementedError...?

also elif

2021-05-25 13:12 UTC, oskusalerma commented on web/domains/case/views.py
> +            url = reverse(
maybe pull this out into prepare_url, it's constructed a few times?

2021-05-26 08:21 UTC, oskusalerma approved these changes

2021-05-26 09:39 UTC, merged