ICMSLST-782 Allow agent to create and edit applications
uktrade/icms pull request #470
Opened 2021-07-06 13:12 UTC by kevinetienne

Update `check_application_permission` to verify if the agent has access to the application (import/export).

- https://github.com/uktrade/icms/commit/145f7fee06aae7528bfb70c607c816de47039906 adds `check_application_permission` where it was missing in import applications and update function arguments when needed;
- https://github.com/uktrade/icms/commit/4b66496c4a9fa99dfafa041b47c62b2eb9054367 adds method `user_is_agent_of_org` used in `check_application_permission` and allow agent on exporter to edit applications;
- https://github.com/uktrade/icms/commit/b5b54e5bcbebd05d288420ddc45b9a244b85e0c1 adds an agent user in `add_dummy_data` command.

2021-07-06 13:48 UTC, MattHolmes123 requested changes

2021-07-06 13:48 UTC, MattHolmes123 commented on web/domains/case/_import/sanctions/views.py
> +def delete_goods(request: AuthenticatedHttpRequest, *, application_pk: int, goods_pk: int):
return type missing

2021-07-06 13:48 UTC, MattHolmes123 commented on web/domains/case/_import/sanctions/views.py
> +def add_supporting_document(request: AuthenticatedHttpRequest, *, pk: int):
return type missing

2021-07-06 13:48 UTC, MattHolmes123 commented on web/domains/case/_import/sanctions/views.py
> +):
return type missing

2021-07-06 13:48 UTC, MattHolmes123 commented on web/domains/case/_import/sanctions/views.py
> +):
return type missing

2021-07-06 13:48 UTC, MattHolmes123 commented on web/domains/case/_import/wood/views.py
> +def add_supporting_document(request: AuthenticatedHttpRequest, *, pk: int):
return type missing

2021-07-06 13:48 UTC, MattHolmes123 commented on web/domains/case/_import/wood/views.py
> +):
return type missing

2021-07-06 13:48 UTC, MattHolmes123 commented on web/domains/case/_import/wood/views.py
> +):
return type missing

2021-07-06 13:48 UTC, MattHolmes123 commented on web/domains/case/_import/wood/views.py
> +):
return type missing

2021-07-06 13:48 UTC, MattHolmes123 commented on web/domains/case/_import/wood/views.py
> +):
return type missing

2021-07-06 13:48 UTC, MattHolmes123 commented on web/management/commands/add_dummy_data.py
> +        user = self.create_superuser(options["password"])
The "admin" user we create day to day should be created with User.objects.create_user.

2021-07-06 13:48 UTC, MattHolmes123 commented on web/management/commands/add_dummy_data.py
> +            agent = User.objects.create(
If you see here I create a user using User.objects.create_user:  
`web/management/commands/add_test_data.py`  
It sets the password correctly etc

2021-07-15 13:14 UTC, kevinetienne commented on web/management/commands/add_dummy_data.py
> +            agent = User.objects.create(
Thanks, I'll copy the same logic you did for adding user when rebasing this branch

2021-07-15 13:26 UTC, kevinetienne commented on web/management/commands/add_dummy_data.py
> +            agent.user_permissions.add(Permission.objects.get(codename=perm))
`importer_access` and `exporter_access` give access in general to create/edit/submit applications. They are 'general' permissions.
`is_agent_of_importer`, `is_agent_of_exporter` are object level permissions.

If we were going to not use `importer_access` and `exporter_access` for `agent` it would mean by extension we could do the same with `contacts` on the `importer` and `exporter`. It would simplify checking creating/editing/submitting applications but it wouldn't allow us to revoke access in general.

If we were going to not use `importer_access` and `exporter_access` for `agent` and use them with `contacts` on the `importer` and `exporter it would means we would have a slightly more complicated check on who can create/edit/submit applications, so maybe it's not worth it.

Hope that helps!

2021-07-15 13:27 UTC, kevinetienne commented on web/tests/domains/case/export/test_views.py
>      def test_no_task(self):
I'll add a few thanks

2021-07-15 13:28 UTC, kevinetienne commented on web/management/commands/add_dummy_data.py
> +        user = self.create_superuser(options["password"])
I'll check what we have with the rebase and I will use `create_user` good point, thanks

2021-07-19 09:53 UTC, MattHolmes123 requested changes

2021-07-19 09:53 UTC, MattHolmes123 commented on web/tests/domains/case/test_views.py
> +def imp_agent_application_user():
I think all these fixtures should be replaced by the newer ones here:  
https://github.com/uktrade/icms/blob/develop/web/tests/conftest.py#L41-L73.
Also your new fixtures should do the data setup here:  
https://github.com/uktrade/icms/blob/develop/web/management/commands/add_test_data.py#L17

The ones you added are copying my bad example where I'm creating users / importers & offices records every test.
If we create the data in add_test_data.py and then create fixtures that only fetch data then it should be quicker.

2021-07-19 09:53 UTC, MattHolmes123 commented on web/tests/domains/case/test_views.py
> +def imp_agent_application_user():
These tests use the better fixtures:  
https://github.com/uktrade/icms/blob/develop/web/tests/domains/case/_import/fa_dfl/test_views.py

2021-07-19 14:13 UTC, kevinetienne commented on web/tests/domains/case/test_views.py
> +def imp_agent_application_user():
fixed in https://github.com/uktrade/icms/pull/470/commits/e277edead7a20a354684b86f3b1e7d3370b7e061 and in https://github.com/uktrade/icms/pull/470/commits/14b5aae757243f245d51bb272d2e20bf569087bf. I've followed your recommendation to not stuff everything (the applications for importer/exporter/agent) in test data.

2021-07-19 14:30 UTC, MattHolmes123 approved these changes

2021-07-19 14:34 UTC, merged