ICMSLST-757 Add Textiles (Quota) response preparation view
uktrade/icms pull request #472
Opened 2021-07-06 16:00 UTC by mikeylockwood

* Add view for response preparation for textiles
* Include link to edit goods using `GoodsTextilesLicenceForm`

2021-07-08 15:46 UTC, kevinetienne commented on web/templates/web/domains/case/import/manage/prepare-response.html
> +{# END MACROS #}
Should we make the other [`application_field`](https://github.com/uktrade/icms/blob/bbb2ffb1cff786fbbc17fb200d65525dff670b5a/web/templates/web/domains/case/import/view_case.html#L17-L28) available more globally?

2021-07-09 08:08 UTC, MattHolmes123 requested changes

2021-07-09 08:08 UTC, MattHolmes123 commented on web/domains/case/_import/textiles/views.py
> +def edit_goods_licence(request: AuthenticatedHttpRequest, application_pk: int) -> HttpResponse:
We have an unwritten rule about view arguments being keyword only (after the request) argument.

2021-07-09 08:08 UTC, MattHolmes123 commented on web/templates/web/domains/case/import/manage/prepare-response.html
> +{# END MACROS #}
We have form macros here:  
`icms/web/templates/forms/fields.html`  
What about a another file for displaying fields when viewing the application / screens like prepare-response? e.g.  
`icms/web/templates/display/fields.html`  
And then add application_section and application_field to there.

2021-07-09 08:08 UTC, MattHolmes123 commented on web/tests/domains/case/_import/textiles/test_admin_views.py
> +
Your tests are failing, I will review them when they are passing :+1:

2021-07-12 07:00 UTC, mikeylockwood commented on web/templates/web/domains/case/import/manage/prepare-response.html
> +{# END MACROS #}
Yes that sounds sensible, will add

2021-07-12 07:36 UTC, mikeylockwood commented on web/domains/case/_import/textiles/views.py
> +def edit_goods_licence(request: AuthenticatedHttpRequest, application_pk: int) -> HttpResponse:
I haven't seen this in any of the other import application views. Happy to change it, but we'd want all the views to be consistent

2021-07-12 08:07 UTC, MattHolmes123 commented on web/domains/case/_import/textiles/views.py
> +def edit_goods_licence(request: AuthenticatedHttpRequest, application_pk: int) -> HttpResponse:
![image](https://user-images.githubusercontent.com/8921101/125252661-8701c280-e2f0-11eb-8d33-5ab1404230c5.png)

2021-07-12 08:07 UTC, MattHolmes123 commented on web/domains/case/_import/textiles/views.py
> +def edit_goods_licence(request: AuthenticatedHttpRequest, application_pk: int) -> HttpResponse:
@mikeylockwood All of these are keyword only arguments after the request parameter.

2021-07-12 10:17 UTC, oskusalerma approved these changes

2021-07-12 10:22 UTC, MattHolmes123 approved these changes

2021-07-12 10:35 UTC, merged