ICMSLST-887 WIP.
uktrade/icms pull request #511
Opened 2021-07-28 15:05 UTC by MattHolmes123

2021-07-29 14:17 UTC, SamDudley requested changes

2021-07-29 14:17 UTC, SamDudley commented on web/static/web/js/pages/cfs-manufacturer-address.js
>      }, 1000);
What about 750?

2021-07-29 14:17 UTC, SamDudley commented on web/static/web/js/pages/cfs-manufacturer-address.js
> +  response.json().then((results) => {
Move `.json()` call up a level.

2021-07-29 14:17 UTC, SamDudley commented on web/templates/partial/js_constants.html
> +  const API_ENDPOINTS = Object.freeze({
Add comment above that this object should contain `key, url`.

2021-07-29 14:28 UTC, SamDudley approved these changes
Looks great to me!

2021-07-30 08:26 UTC, oskusalerma approved these changes

2021-07-30 08:28 UTC, kevinetienne approved these changes

2021-07-30 08:31 UTC, merged