ICMSLST-339: CFS Schedule product spreadsheet upload
uktrade/icms pull request #540
Opened 2021-08-11 16:24 UTC by mikeylockwood

2021-08-12 11:38 UTC, MattHolmes123 requested changes

2021-08-12 11:38 UTC, MattHolmes123 commented on web/domains/case/export/views.py
> +                    else:
rather than if / else couldn't this be:

```
if product_type_number not in existing_product_type_numbers:
    # do stuff
```

2021-08-12 12:49 UTC, mikeylockwood commented on web/domains/case/export/utils.py
> +from collections import OrderedDict
Originally I had a file there for doing more generic xlsx operations.  A lot of the logic regarding the CFS Schedule products is tightly coupled to the CFSSchedule models so I would prefer to keep the utils file in the same directory

2021-08-12 12:50 UTC, mikeylockwood commented on web/domains/case/export/utils.py
> +    products_file: S3Boto3StorageFile, is_biocidal: bool = False
I think there is some middleware or something that is wrapping the file into a `S3Boto3StorageFile` in the request and performing virus checks on it. It is definitely this type when I read it from the request

2021-08-12 12:58 UTC, mikeylockwood commented on web/domains/case/export/views.py
> +                            msg = f"active ingredient name: {name} CAS number: {cas_number}"
This else is for any other error in the form that isn't on one of the fields. I don't really expect that to ever happen

2021-08-12 14:11 UTC, MattHolmes123 commented on web/domains/case/export/utils.py
> +    products_file: S3Boto3StorageFile, is_biocidal: bool = False
Ahh yes I think you're right! I forgot its the middleware that does the virus checking. 
But if thats the case is it being uploaded to s3 as well??
Because we never want that right?
Something to look in to / confirm

2021-08-12 14:33 UTC, MattHolmes123 commented on web/domains/case/export/utils.py
> +from collections import OrderedDict
Thinking about it we haven't even split out any of the export code.
its all in `/export/*.py` anyway.

2021-08-12 14:56 UTC, mikeylockwood commented on web/domains/case/export/views.py
> +                            msg = f"active ingredient name: {name} CAS number: {cas_number}"
They can have errors at the same time, it will only show the error for one field at time though. If they correct that error and re upload it will then show the error for the other field. I didn't want there to be too much content in the flash message. There might be a better way of delivering the errors on the page so that all errors for all of the rows can be displayed at once

2021-08-12 15:13 UTC, mikeylockwood commented on web/static/web/js/pages/cfs-schedule-edit.js
> +  productUpload.addEventListener("change", (e) => {
This was just because I hid the input and used a label with the same classes that were used in legacy. I can just remove the label and the classes. I don't think the django form adds much here

2021-08-13 12:16 UTC, kevinetienne commented on web/domains/case/export/utils.py
> +            product_type = int(float(val))
I think you can skip one step by not calling `strip`

```python
>>> [int(float(x)) for x in [' 1.2', '2.3 ', ' 3.4 ']]
[1, 2, 3]
```

2021-08-13 13:20 UTC, kevinetienne approved these changes

2021-08-16 09:07 UTC, MattHolmes123 requested changes

2021-08-16 09:07 UTC, MattHolmes123 commented on web/domains/case/export/views.py
> +
@kevinetienne what do you think?

2021-08-16 09:10 UTC, mikeylockwood commented on web/domains/case/export/utils.py
> +            product_product_type_numbers = list(product.product_type_numbers)
Casting to a list makes a copy of the list rather than mutating it

2021-08-16 09:14 UTC, mikeylockwood commented on web/domains/case/export/utils.py
> +            filename=io.BytesIO(chunk), read_only=True, data_only=True
Processing the file in chunks is to protect the memory. If someone uploads a huge file and the code tries to read the whole thing, we could be hit with a OOM issue

2021-08-16 09:17 UTC, kevinetienne commented on web/domains/case/export/views.py
> +
I like the idea to skip the `S3FileUploadHandler`. It feels straightforward enough to add an exception in the view and it's documented.

By testing do you mean adding test for this view? I know we could call `assert_not_called` on the S3 uploader but I don't know how integration we have in those tests?

2021-08-16 09:21 UTC, MattHolmes123 commented on web/domains/case/export/views.py
> +
Cool, well lets go for the approach detailed on the django docs then.
(a csrf except function that removes the s3 uploader and then calls the real view

2021-08-16 09:27 UTC, mikeylockwood commented on web/domains/case/export/utils.py
> +        for row_values in sheet.values:
`row` is to retain the row number when iterating over the chunks. I start at 0 and increment the row number at the start so to not have to increment the row number in multiple places

2021-08-16 13:21 UTC, MattHolmes123 commented on web/domains/case/export/utils.py
> +        for row_values in sheet.values:
You do this:
`row = 0`
and the next time row is referenced you do this:
`row += 1`

Rather than incrementing a counter its easier / pythonic to do this or am I missing something else?:
`for row, row_data in enumerate(sheet.values, start=1)`

2021-08-16 13:33 UTC, MattHolmes123 commented on web/domains/case/export/utils.py
> +            filename=io.BytesIO(chunk), read_only=True, data_only=True
I asked originally as I was asking if the loop would still work after the first chunk but now I've had another look at _extract_sheet_header I see it only checks if the header is valid in the first chunk.

2021-08-16 13:52 UTC, MattHolmes123 commented on web/domains/case/export/utils.py
> +            product_product_type_numbers = list(product.product_type_numbers)
Made thoughts known on slack :)

2021-08-17 06:27 UTC, MattHolmes123 requested changes

2021-08-17 06:27 UTC, MattHolmes123 commented on web/domains/case/export/utils.py
> +    """
Multi-line docstrings should have a summary line, then an empty line followed by a detailed description.
https://www.python.org/dev/peps/pep-0257/#multi-line-docstrings

2021-08-17 06:27 UTC, MattHolmes123 commented on web/domains/case/export/utils.py
> +    Combines product type numbers and ingredients for the wach product.
You've got a typo "wach product"

2021-08-17 06:27 UTC, MattHolmes123 commented on web/domains/case/export/views.py
> +                return redirect(
I think we should get rid of the finally as its behavior is confusing when using with return statements:
![image](https://user-images.githubusercontent.com/8921101/129673745-d46d24cc-8d2c-4003-b02c-4dfd35a19359.png)

I think we should do this (not real code obviously):
```
try:
    process_file()
    delete_file()

    return some_redirect()

except ValueError as err:
        messages.warning(request, f"Upload failed: {err}")
        delete_file()

except Exception:
        messages.warning(request, "Upload failed: An unknown error occurred")
        delete_file()
        capture_exception()
        
return some_redirect()        
```

2021-08-17 06:27 UTC, MattHolmes123 commented on web/domains/case/export/views.py
> +                raise ValueError("No valid file found. Please upload the spreadsheet.")
Instead of raising a ValueError here just display the error from the form and add as a `messages.warning()`.  
That way all ValueError's only come from the the processing code (where the file is valid according to djangos form validation).

2021-08-17 09:18 UTC, MattHolmes123 approved these changes

2021-08-17 09:28 UTC, merged