ICMSLST-943 Authorise documents view
uktrade/icms pull request #573
Opened 2021-08-31 12:47 UTC by mikeylockwood

2021-08-31 14:57 UTC, MattHolmes123 commented on web/domains/case/forms.py
> +    def clean_password(self) -> None:
Is everything clean at this point?

as in why not do this in the main clean method?
e.g.

```
    def clean(self) -> Dict[str, Any]:
        cleaned_data = super().clean()
        
        # Do extra password cleaning
```

2021-08-31 14:57 UTC, MattHolmes123 commented on web/domains/case/forms.py
> +    def clean_password(self) -> None:
I can never remember where the `def clean_field()` methods are called in the django form logic

2021-08-31 14:59 UTC, oskusalerma requested changes

2021-08-31 14:59 UTC, oskusalerma commented on web/domains/case/forms.py
> +
clean_ methods need to return the value, so `return password` here?

2021-08-31 14:59 UTC, oskusalerma commented on web/domains/case/views.py
> +                return redirect(reverse("workbasket"))
should we use django.messages to show some message here? being dumped to workbasket is a big jump. "authorized case XXX..." kind of message

2021-08-31 14:59 UTC, MattHolmes123 commented on web/domains/case/views.py
> +                task_type,
Did you mean to leave this `,` in?

2021-08-31 15:02 UTC, kevinetienne commented on web/domains/case/views.py
> +def authorise_documents(
do we need to list the password as sensitive see https://docs.djangoproject.com/en/3.2/howto/error-reporting/#filtering-sensitive-information

2021-08-31 15:02 UTC, kevinetienne commented on web/domains/case/forms.py
> +from django.contrib.auth import authenticate
do we need to use `authenticate` from https://github.com/uktrade/icms/blob/3a1e0c9f6fde79345c1d08573bd982eeda1c26bb/web/auth/models.py#L7?

2021-08-31 15:03 UTC, mikeylockwood commented on web/domains/case/views.py
> +                return redirect(reverse("workbasket"))
I think there will be more to do here regarding validaiton and digital signing. I will find a relevent ticket number and add a TODO

2021-08-31 15:04 UTC, mikeylockwood commented on web/domains/case/forms.py
> +    def clean_password(self) -> None:
Yeah I can move this to the clean method instead

2021-08-31 15:04 UTC, mikeylockwood commented on web/domains/case/forms.py
> +from django.contrib.auth import authenticate
I would think so, yes

2021-08-31 15:12 UTC, mikeylockwood commented on web/domains/case/forms.py
> +from django.contrib.auth import authenticate
Actually looking at this, it looks like this is a custom backend added for login. It seems to authenticate with Django's authenticate and then adds login attempts on failure. Do we want something similar for a user that is already logged in?

2021-08-31 15:17 UTC, mikeylockwood commented on web/domains/case/views.py
> +def authorise_documents(
I wasn't sure as the authenticate call marks it as sensitive but I guess it could error before hitting that

2021-09-01 07:08 UTC, kevinetienne commented on web/domains/case/forms.py
> +from django.contrib.auth import authenticate
You're right, the user is already logged in, we don't need those checks. Thanks!

2021-09-01 07:20 UTC, MattHolmes123 commented on web/domains/case/forms.py
> +from django.contrib.auth import authenticate
The password check is a measure to prevent other people authorising it from your machine I guess?  It doesn't really matter that the user is logged in I suppose.

2021-09-01 07:48 UTC, mikeylockwood commented on web/domains/case/forms.py
> +from django.contrib.auth import authenticate
So looking into this, calling django authenticate does use the custom backend as it gets it from the settings. It also does suspend the account if the user is already logged in. However, if the user is logged in, the suspension currently doesn't affect the user until they log out

2021-09-01 08:08 UTC, mikeylockwood commented on web/domains/case/forms.py
> +from django.contrib.auth import authenticate
Added a check to see if the user is authenticated

2021-09-01 08:48 UTC, kevinetienne commented on web/domains/case/views.py
> +            Task.objects.create(process=application, task_type="authorise", previous=task)
Looks like you need to update cancel authorisation too now. As it would except a new state.

See https://github.com/uktrade/icms/blob/3a1e0c9f6fde79345c1d08573bd982eeda1c26bb/web/domains/case/views.py#L2127-L2145

2021-09-01 08:48 UTC, kevinetienne commented on web/domains/case/views.py
> +def authorise_documents(
You are right and I would still add it to the view to prevent to leak the ilb admin password or any password on a 3rd party platform for example (sentry, aws...). This is how you can add it:

```python
@login_required
@permission_required("web.reference_data_access", raise_exception=True)
@sensitive_post_parameters("password")
def authorise_documents(
```

I'm not sure if you need to have `sensitive_variables` in the form after adding the filter to view. This is when looking at what django does:

see
https://github.com/django/django/blob/af10e97531a59e4af09b5ec0c1a3ea476f2b6015/django/contrib/auth/views.py#L52
https://github.com/django/django/blob/af10e97531a59e4af09b5ec0c1a3ea476f2b6015/django/contrib/auth/forms.py#L163

2021-09-01 08:49 UTC, kevinetienne commented on web/domains/case/views.py
> +    request: AuthenticatedHttpRequest, *, application_pk: int, case_type: str
You are right and I would still add it to the view to prevent to leak the ilb admin password or any password on a 3rd party platform for example (sentry, aws...). This is how you can add it:

```python
@login_required
@permission_required("web.reference_data_access", raise_exception=True)
@sensitive_post_parameters("password")
def authorise_documents(
```

I'm not sure if you need to have `sensitive_variables` in the form after adding the filter to view. This is when looking at what django does:

see
https://github.com/django/django/blob/af10e97531a59e4af09b5ec0c1a3ea476f2b6015/django/contrib/auth/views.py#L52
https://github.com/django/django/blob/af10e97531a59e4af09b5ec0c1a3ea476f2b6015/django/contrib/auth/forms.py#L163

2021-09-01 08:58 UTC, oskusalerma requested changes

2021-09-01 08:58 UTC, oskusalerma commented on web/domains/case/views.py
> +                # TODO: ICMSLST-809 Check validation that is needed when generating license file
finish task here, set owner etc

2021-09-01 09:43 UTC, oskusalerma approved these changes

2021-09-01 09:47 UTC, merged