ICMSLST-1117 Remove statuses for fir, withdrawal, update requests and chief
uktrade/icms pull request #609
Opened 2021-09-21 10:40 UTC by kevinetienne

Having a status for them make it impossible to have them simultaneously,
ex: user withdraw application, case owner requests further information
and ask for an update request.

We now depends on the relationship to check if we have a request to
withdraw, firs and an update request.

2021-09-21 12:53 UTC, mikeylockwood commented on web/domains/case/models.py
> +            elif task and task.task_type == Task.TaskType.PROCESS:
So if lines 376 and 379 are both `False` then the `view_action` won't be in the workbasket?

2021-09-21 13:03 UTC, mikeylockwood approved these changes

2021-09-21 13:13 UTC, kevinetienne commented on web/domains/case/models.py
> +            elif task and task.task_type == Task.TaskType.PROCESS:
The view doesn't seems to appear when bypassing chief but yeah it's appearing when authorising the documents, I'll add it thanks!

2021-09-21 13:47 UTC, MattHolmes123 commented on web/utils/search.py
> +    filters = Q(status=case_status)
I'm trying to think of the best way to refactor it.

2021-09-21 13:51 UTC, kevinetienne commented on web/utils/search.py
> +    filters = Q(status=case_status)
`FIR_REQUESTED` and `UPDATE_REQUESTED` are the exceptions. They should always have the `PROCESSING` state associated to them.

2021-09-21 13:53 UTC, MattHolmes123 commented on web/utils/search.py
> +    filters = Q(status=case_status)
I think this will work:
```
def _get_status_to_filter(case_status: str) -> Q:
    st = ImportApplication.Statuses

    choices = dict(get_import_status_choices())
    if case_status not in choices:
        raise NotImplementedError(f"Filter ({case_status}) for case status not supported.")

    filters = Q()

    # Only filter on real statuses
    if case_status in ImportApplication.Statuses:
        filters = Q(status=case_status)

    if case_status in ("FIR_REQUESTED", st.PROCESSING):
        filters |= Q(further_information_requests__status=FurtherInformationRequest.OPEN)

    elif case_status in ("UPDATE_REQUESTED", st.PROCESSING):
        filters |= Q(update_requests__status=UpdateRequest.Status.OPEN)

    return filters
```

2021-09-21 14:21 UTC, MattHolmes123 requested changes

2021-09-21 14:21 UTC, MattHolmes123 commented on web/domains/case/models.py
> +            if self.withdrawals.filter(status=WithdrawApplication.STATUS_OPEN).filter(
Only one call to filter needed.

2021-09-21 14:21 UTC, MattHolmes123 commented on web/domains/case/models.py
> +            if self.withdrawals.filter(status=WithdrawApplication.STATUS_OPEN).filter(
Same here (and anywhere else) :)

2021-09-21 14:21 UTC, MattHolmes123 commented on web/domains/case/models.py
> +        update_requests = self.update_requests.filter(current).filter(is_active=True)
one more for good luck :)

2021-09-21 14:21 UTC, MattHolmes123 commented on web/domains/case/models.py
> +            applicant_actions = self._get_applicant_actions(view_action, task, kwargs)
General comment about `def get_workbasket_row`.
We have changed this a few times and I think we should have had tests for it a long time a go.
Its getting quite complex now.

2021-09-21 14:21 UTC, MattHolmes123 commented on web/domains/case/models.py
> +            models.Q(status=UpdateRequest.Status.OPEN)
`status__in=[st.OPEN, st.UPDATE_IN_PROGRESS, st.RESPONDED]`

2021-09-21 14:21 UTC, MattHolmes123 commented on web/domains/case/views/views_fir.py
> +                    # Ideally a FIR will inherit from Process and it will have it's own task
Are you planning on doing anything with these comments?
You've left them in a few places.

2021-09-21 14:33 UTC, kevinetienne commented on web/domains/case/views/views_fir.py
> +                    # Ideally a FIR will inherit from Process and it will have it's own task
Removed in https://github.com/uktrade/icms/pull/609/commits/296885ea7641c1ab08fc776f75d709a12f383a9c

2021-09-21 14:34 UTC, kevinetienne commented on web/domains/case/models.py
> +            models.Q(status=UpdateRequest.Status.OPEN)
Updated in https://github.com/uktrade/icms/pull/609/commits/296885ea7641c1ab08fc776f75d709a12f383a9c

2021-09-21 14:34 UTC, kevinetienne commented on web/domains/case/models.py
> +        update_requests = self.update_requests.filter(current).filter(is_active=True)
Updated in https://github.com/uktrade/icms/pull/609/commits/296885ea7641c1ab08fc776f75d709a12f383a9c

2021-09-21 14:34 UTC, kevinetienne commented on web/domains/case/models.py
> +            if self.withdrawals.filter(status=WithdrawApplication.STATUS_OPEN).filter(
Updated in https://github.com/uktrade/icms/pull/609/commits/296885ea7641c1ab08fc776f75d709a12f383a9c

2021-09-21 14:34 UTC, kevinetienne commented on web/domains/case/models.py
> +            if self.withdrawals.filter(status=WithdrawApplication.STATUS_OPEN).filter(
Updated in https://github.com/uktrade/icms/pull/609/commits/296885ea7641c1ab08fc776f75d709a12f383a9c

2021-09-22 09:15 UTC, kevinetienne commented on web/domains/case/models.py
> +            applicant_actions = self._get_applicant_actions(view_action, task, kwargs)
Added tests in https://github.com/uktrade/icms/pull/609/commits/3e2e64a4ce13e84e04bc099c5e764c0fff20f561

2021-09-22 10:59 UTC, MattHolmes123 approved these changes

2021-09-22 12:58 UTC, merged