ICMSLST-1035 Add wildcard filter function for searching applications.
uktrade/icms pull request #619
Opened 2021-09-29 10:48 UTC by MattHolmes123

2021-09-29 11:31 UTC, oskusalerma requested changes

2021-09-29 11:31 UTC, oskusalerma commented on web/utils/search.py
> +    """Strings with `%` are converted into django orm code using one of several methods.
s/orm/ORM/

2021-09-29 11:31 UTC, oskusalerma commented on web/utils/search.py
> +    search = {f"{field}__iregex": f"^{search_regex}"}
if we're doing regex search, do we need to escape regex characters in user supplied string?

2021-09-29 12:27 UTC, MattHolmes123 commented on web/utils/search.py
> +    search = {f"{field}__iregex": f"^{search_regex}"}
Probably, I haven't really thought about it yet

2021-09-29 12:47 UTC, MattHolmes123 commented on web/utils/search.py
> +    search = {f"{field}__iregex": f"^{search_regex}"}
Added a subtask for this.

2021-10-04 08:18 UTC, mikeylockwood commented on web/utils/search.py
> +    search = {f"{field}__iregex": f"^{search_regex}"}
Does the regex need to be escaped before creating a regex search?

```
search_regex = re.escape(search_pattern).replace("//%", ".*")
"""

2021-10-04 08:20 UTC, mikeylockwood commented on web/utils/search.py
> +    search = {f"{field}__iregex": f"^{search_regex}"}
Maybe that won't work with  `istartswith` and `iendswith` below

2021-10-04 08:26 UTC, MattHolmes123 commented on web/utils/search.py
> +    search = {f"{field}__iregex": f"^{search_regex}"}
I have a story to escape the regex later.
re.escape isn't necessarily the correct thing to do.

2021-10-04 08:28 UTC, mikeylockwood approved these changes

2021-10-04 08:31 UTC, kevinetienne approved these changes

2021-10-04 08:36 UTC, merged