ICMSLST-1914 Cover letter templates
uktrade/icms pull request #987
Opened 2023-02-24 11:28 UTC by mikeylockwood

2023-02-24 14:04 UTC, MattHolmes123 requested changes

2023-02-24 14:04 UTC, MattHolmes123 commented on web/tests/domains/template/test_utils.py
> +)
Based on my earlier comments I thing we should change these tests.

1. Don't support optionals 
2. Don't support unknown placeholders
3. We could get fancy with our context, DEATH to inline dictionaries everywhere!

2023-02-24 14:04 UTC, MattHolmes123 commented on web/tests/domains/template/test_utils.py
> +    context = get_cover_letter_context(app, final=True)
if this indeed testing a final cover letter template then we should be testing the correct licence details are shown not checking for None.
Create a draft licence for the app you've created.

2023-02-24 14:22 UTC, mikeylockwood commented on web/domains/template/utils.py
> +            "LICENCE_END_DATE": licence and licence_end_date,
Will also be using the function to validate placeholders in ICMSLST-1921. At this point there may not be a licence yet but the licence placeholder should still be valid in the editor

2023-02-24 14:24 UTC, mikeylockwood commented on web/domains/template/utils.py
> +        return content
76 can never be `None` because if `content is None` it returns an empty string on 73. Will remove 75 and 76 though if not needed

2023-02-24 14:28 UTC, mikeylockwood commented on web/domains/template/utils.py
> +        content = re.sub(TEMPLATE_CONTENT_REGEX.format(replacement), str(value), content)
I know the replacement implementation is not finished yet.  I was only doing enough to be able to implement the cover letters in this ticket. 
I think I want to be able to also retrieve all keys for validation but will think about it more in ICMSLST-1921

2023-02-24 14:32 UTC, mikeylockwood commented on web/domains/template/utils.py
> +            add_application_cover_letter(application, template)
`cover_letter_flag` will be `True` for `SILApplication` but needs to be manually set rather than automatically. Could add a pass and a comment there I guess and then a value error

2023-02-24 14:33 UTC, mikeylockwood commented on web/tests/domains/template/test_utils.py
> +    context = get_cover_letter_context(app, final=True)
Extending the test as part of my in progress ticket where the cover letter data will be used to generate the cover letter as the licence will have been created at that point

ICMSLST-1917

2023-02-24 14:35 UTC, mikeylockwood commented on web/domains/template/utils.py
> +        content = re.sub(TEMPLATE_CONTENT_REGEX.format(replacement), str(value), content)
Nice idea fora context class

2023-02-24 14:50 UTC, MattHolmes123 commented on web/domains/template/utils.py
> +        return content
I read this as 
```
if context is None:
    return context
```

2023-03-01 11:34 UTC, MattHolmes123 requested changes

2023-03-01 11:34 UTC, MattHolmes123 commented on web/domains/template/utils.py
> +CONTEXT_VARIABLE_REGEX = r"\[\[([A-Z]+(_[A-Z]+)*)\]\]"
This regex has multiple matching groups which is a bit strange.
e.g. `APP_REF_VALUE` would return a match with two values `('APP_REF_VALUE', '_VALUE')`

It also doesn't support lower case letters.
This regex works: `\[\[([A-Za-z_]+)]]` or better yet use regex flags to make it more clear what is happening and we can also ignore case:
```
CONTEXT_VARIABLE_REGEX = re.compile(
    r"""
        \[\[        # Opening braces
        ([a-z_]+)   # Match group of a-z and underscore
        ]]          # Closing braces
    """,
    flags=re.IGNORECASE | re.VERBOSE,
)
```

2023-03-01 11:34 UTC, MattHolmes123 commented on web/domains/template/utils.py
> +    return {hit[0]: context[hit[0]] for hit in set(re.findall(CONTEXT_VARIABLE_REGEX, content))}
Using my regex means you won't need to index in to each hit (as each hit matches one value)

2023-03-01 11:34 UTC, MattHolmes123 commented on web/domains/template/utils.py
> +TEMPLATE_CONTENT_REGEX = r"\[\[{}\]\]"
The `\` isn't need for the closing brakets if the opening ones have been escaped.

This will work: `r"\[\[{}]]"`

2023-03-01 11:34 UTC, MattHolmes123 commented on web/domains/template/utils.py
> +ContextT = CoverLetterTemplateContext
ContextT should be replaced with a protocol if this is going to be extended later.

```
from typing import Protocol

class TemplateContextProcessor(Protocol):
    def __init__(self, application: ImportApplication, *args, **kwargs):
        ...

    def __getitem__(self, item: str) -> str:
        ...
```

2023-03-01 11:34 UTC, MattHolmes123 commented on web/domains/template/utils.py
> +ContextT = CoverLetterTemplateContext
I did args / kwargs instead of document type as that might not be required for other TemplateContextProcessor classes.

2023-03-01 11:34 UTC, MattHolmes123 commented on web/domains/template/utils.py
> +ContextT = CoverLetterTemplateContext
But either way right now you're saying every ContextT class will be a cover letter template processor

2023-03-01 13:15 UTC, MattHolmes123 approved these changes

2023-03-01 13:27 UTC, merged