ICMSLST-1917 Cover Letter PDF
uktrade/icms pull request #995
Opened 2023-03-09 08:50 UTC by mikeylockwood

2023-03-09 14:27 UTC, MattHolmes123 requested changes

2023-03-09 14:27 UTC, MattHolmes123 commented on web/templates/pdf/import/cover-letter.html
> +    <link rel="icon" href="{{ static('web/img/favicon.png') }}" type="image/png">
Do we need this?

2023-03-09 14:27 UTC, MattHolmes123 commented on web/templates/pdf/import/cover-letter.html
> +    {% endif -%}
This if else block feels like you've copied it from somewhere else.
Do we need a title for a cover letter template?

2023-03-09 14:27 UTC, MattHolmes123 commented on web/templates/pdf/import/cover-letter.html
> +<html>
Missing required 'lang' attribute 
`<html lang="en">`

2023-03-09 14:27 UTC, MattHolmes123 commented on web/templates/pdf/import/cover-letter.html
> +          <p class="address-line">TS23 2NF</p>  <!-- /PS-IGNORE -->
I wonder if this should be configurable somehow?
```
{% for line in ilb_address %}
  <p class="address-line">{{line}}</p>
{% endfor %}
```
Could always sort it later I suppose.

2023-03-09 14:27 UTC, MattHolmes123 commented on web/templates/pdf/import/cover-letter.html
> +          <span class="url">gov.uk/dbt</span>
I get page not found going to this url: `https://www.gov.uk/dbt`

2023-03-09 14:27 UTC, MattHolmes123 commented on web/templates/pdf/import/cover-letter.html
> +    {% endif %}
If this were me I wouldn't have this `if else endif` logic in the template.
I'd supply a list of endorsements in the context.
e.g. something like this
```
if preview:
    endorsements = ["[[ ADDITIONAL_REMARKS ]]"]
else:
    endorsements = process.endorsements.values_list("content", flat=True")
```
The less logic in the template the better - templates should be as dumb as they can be

2023-03-09 14:27 UTC, MattHolmes123 commented on web/tests/domains/template/test_utils.py
> +from web.domains.case._import.fa_dfl.models import DFLApplication
we can import all models from `web.models` .

2023-03-09 14:27 UTC, MattHolmes123 commented on web/tests/domains/template/test_utils.py
> +from web.domains.case._import.fa_dfl.models import DFLApplication
Just seen further down you've deleted the existing imports from web.models I don't understand why.
Importing from web.models allows for easier refactoring as if you change the underlying structure web.models isn't going anywhere

2023-03-09 14:31 UTC, mikeylockwood commented on web/domains/template/context.py
> +    def __init__(self, application: "ImportApplication", document_type):
Trying to figure out why DocumentTypes was causing a circular import and forgot to put it back in

2023-03-09 14:37 UTC, mikeylockwood commented on web/tests/domains/template/test_utils.py
> +from web.domains.case._import.fa_dfl.models import DFLApplication
It was again part of trying to figure out the circular import

2023-03-09 14:51 UTC, mikeylockwood commented on web/templates/pdf/import/cover-letter.html
> +    <link rel="icon" href="{{ static('web/img/favicon.png') }}" type="image/png">
Yes as it doesn't inherit from the base template. The favicon image seems to just be a placeholder at the minute so will need to be replaced at some point

2023-03-09 15:33 UTC, mikeylockwood commented on web/templates/pdf/import/cover-letter.html
> +    {% endif %}
I want different classes for the p elements still. It is nicer just to do this in the template

2023-03-09 16:45 UTC, mikeylockwood commented on web/templates/pdf/import/cover-letter.html
> +          <span class="url">gov.uk/dbt</span>
I'll just update wit when it's created if that makes you happy. The dit link says this page has a big banner saying this organisation is changing so will need to be updated

2023-03-10 08:55 UTC, MattHolmes123 commented on web/templates/pdf/import/cover-letter.html
> +    {% endif %}
Oh yer I just noticed the extra class on the p tag.
You could still do that without the neeed for the if else and django db logic in the template.

2023-03-10 11:14 UTC, MattHolmes123 approved these changes

2023-03-10 11:18 UTC, MattHolmes123 reviewed
It is generating cover letters for sanctions applications

2023-03-10 11:55 UTC, merged